-- 01_create_databases.sql
CREATE WAREHOUSE IF NOT EXISTS ADVENTUREWORKS_ETL_WH
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE IF NOT EXISTS ADVENTUREWORKS_BI_WH
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS ADVENTUREWORKS_MIGRATED;

CREATE SCHEMA IF NOT EXISTS ADVENTUREWORKS_MIGRATED.STAGING;
CREATE SCHEMA IF NOT EXISTS ADVENTUREWORKS_MIGRATED.DW;
CREATE SCHEMA IF NOT EXISTS ADVENTUREWORKS_MIGRATED.UTILITY;
