-- 04_create_file_formats.sql
CREATE OR REPLACE FILE FORMAT ADVENTUREWORKS_MIGRATED.UTILITY.ff_csv
  TYPE = CSV
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  EMPTY_FIELD_AS_NULL = TRUE
  NULL_IF = ('', 'NULL', 'null');

CREATE OR REPLACE FILE FORMAT ADVENTUREWORKS_MIGRATED.UTILITY.ff_parquet
  TYPE = PARQUET
  COMPRESSION = AUTO;
