-- 05_create_stages.sql
CREATE OR REPLACE STAGE ADVENTUREWORKS_MIGRATED.STAGING.csv_internal_stage
  FILE_FORMAT = ADVENTUREWORKS_MIGRATED.UTILITY.ff_csv;

CREATE OR REPLACE STAGE ADVENTUREWORKS_MIGRATED.STAGING.parquet_internal_stage
  FILE_FORMAT = ADVENTUREWORKS_MIGRATED.UTILITY.ff_parquet;

CREATE OR REPLACE STAGE ADVENTUREWORKS_MIGRATED.STAGING.raw_internal_stage;
