-- load_dw.sql
-- Loads data from STAGING to DW using SCD Type 2 for dimensions and upsert MERGE for fact tables.
USE DATABASE ADVENTUREWORKS_MIGRATED;
USE SCHEMA DW;

SELECT 'Starting DW load from STAGING schema' AS status;

SELECT 'Applying SCD Type 2 for DW.dim_account from STAGING.dim_account_stg' AS status;
MERGE INTO ADVENTUREWORKS_MIGRATED.DW.dim_account AS tgt
USING (
  SELECT src.*, SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(src."PARENTACCOUNTKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."ACCOUNTCODEALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."PARENTACCOUNTCODEALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."ACCOUNTDESCRIPTION"), '__NULL__'), COALESCE(TO_VARCHAR(src."ACCOUNTTYPE"), '__NULL__'), COALESCE(TO_VARCHAR(src."OPERATOR"), '__NULL__'), COALESCE(TO_VARCHAR(src."CUSTOMMEMBERS"), '__NULL__'), COALESCE(TO_VARCHAR(src."VALUETYPE"), '__NULL__'), COALESCE(TO_VARCHAR(src."CUSTOMMEMBEROPTIONS"), '__NULL__')), 256) AS src_hash
  FROM ADVENTUREWORKS_MIGRATED.STAGING.dim_account_stg AS src
) AS src
ON tgt."ACCOUNTKEY" = src."ACCOUNTKEY"
  AND tgt."_IS_CURRENT" = TRUE
WHEN MATCHED AND (SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(tgt."PARENTACCOUNTKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ACCOUNTCODEALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."PARENTACCOUNTCODEALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ACCOUNTDESCRIPTION"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ACCOUNTTYPE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."OPERATOR"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."CUSTOMMEMBERS"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."VALUETYPE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."CUSTOMMEMBEROPTIONS"), '__NULL__')), 256) <> src.src_hash) THEN
  UPDATE SET tgt."_IS_CURRENT" = FALSE, tgt."_VALID_TO" = CURRENT_TIMESTAMP();

MERGE INTO ADVENTUREWORKS_MIGRATED.DW.dim_account AS tgt
USING (
  SELECT src.*, SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(src."PARENTACCOUNTKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."ACCOUNTCODEALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."PARENTACCOUNTCODEALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."ACCOUNTDESCRIPTION"), '__NULL__'), COALESCE(TO_VARCHAR(src."ACCOUNTTYPE"), '__NULL__'), COALESCE(TO_VARCHAR(src."OPERATOR"), '__NULL__'), COALESCE(TO_VARCHAR(src."CUSTOMMEMBERS"), '__NULL__'), COALESCE(TO_VARCHAR(src."VALUETYPE"), '__NULL__'), COALESCE(TO_VARCHAR(src."CUSTOMMEMBEROPTIONS"), '__NULL__')), 256) AS src_hash
  FROM ADVENTUREWORKS_MIGRATED.STAGING.dim_account_stg AS src
) AS src
ON tgt."ACCOUNTKEY" = src."ACCOUNTKEY"
  AND tgt."_IS_CURRENT" = TRUE
  AND (SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(tgt."PARENTACCOUNTKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ACCOUNTCODEALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."PARENTACCOUNTCODEALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ACCOUNTDESCRIPTION"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ACCOUNTTYPE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."OPERATOR"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."CUSTOMMEMBERS"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."VALUETYPE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."CUSTOMMEMBEROPTIONS"), '__NULL__')), 256) = src.src_hash)
WHEN NOT MATCHED THEN
  INSERT ("ACCOUNTKEY", "PARENTACCOUNTKEY", "ACCOUNTCODEALTERNATEKEY", "PARENTACCOUNTCODEALTERNATEKEY", "ACCOUNTDESCRIPTION", "ACCOUNTTYPE", "OPERATOR", "CUSTOMMEMBERS", "VALUETYPE", "CUSTOMMEMBEROPTIONS", "_VALID_FROM", "_VALID_TO", "_IS_CURRENT")
  VALUES (src."ACCOUNTKEY", src."PARENTACCOUNTKEY", src."ACCOUNTCODEALTERNATEKEY", src."PARENTACCOUNTCODEALTERNATEKEY", src."ACCOUNTDESCRIPTION", src."ACCOUNTTYPE", src."OPERATOR", src."CUSTOMMEMBERS", src."VALUETYPE", src."CUSTOMMEMBEROPTIONS", CURRENT_TIMESTAMP(), NULL, TRUE);

SELECT 'Applying SCD Type 2 for DW.dim_currency from STAGING.dim_currency_stg' AS status;
MERGE INTO ADVENTUREWORKS_MIGRATED.DW.dim_currency AS tgt
USING (
  SELECT src.*, SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(src."CURRENCYALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."CURRENCYNAME"), '__NULL__')), 256) AS src_hash
  FROM ADVENTUREWORKS_MIGRATED.STAGING.dim_currency_stg AS src
) AS src
ON tgt."CURRENCYKEY" = src."CURRENCYKEY"
  AND tgt."_IS_CURRENT" = TRUE
WHEN MATCHED AND (SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(tgt."CURRENCYALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."CURRENCYNAME"), '__NULL__')), 256) <> src.src_hash) THEN
  UPDATE SET tgt."_IS_CURRENT" = FALSE, tgt."_VALID_TO" = CURRENT_TIMESTAMP();

MERGE INTO ADVENTUREWORKS_MIGRATED.DW.dim_currency AS tgt
USING (
  SELECT src.*, SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(src."CURRENCYALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."CURRENCYNAME"), '__NULL__')), 256) AS src_hash
  FROM ADVENTUREWORKS_MIGRATED.STAGING.dim_currency_stg AS src
) AS src
ON tgt."CURRENCYKEY" = src."CURRENCYKEY"
  AND tgt."_IS_CURRENT" = TRUE
  AND (SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(tgt."CURRENCYALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."CURRENCYNAME"), '__NULL__')), 256) = src.src_hash)
WHEN NOT MATCHED THEN
  INSERT ("CURRENCYKEY", "CURRENCYALTERNATEKEY", "CURRENCYNAME", "_VALID_FROM", "_VALID_TO", "_IS_CURRENT")
  VALUES (src."CURRENCYKEY", src."CURRENCYALTERNATEKEY", src."CURRENCYNAME", CURRENT_TIMESTAMP(), NULL, TRUE);

SELECT 'Applying SCD Type 2 for DW.dim_customer from STAGING.dim_customer_stg' AS status;
MERGE INTO ADVENTUREWORKS_MIGRATED.DW.dim_customer AS tgt
USING (
  SELECT src.*, SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(src."GEOGRAPHYKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."CUSTOMERALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."TITLE"), '__NULL__'), COALESCE(TO_VARCHAR(src."FIRSTNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."MIDDLENAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."LASTNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."NAMESTYLE"), '__NULL__'), COALESCE(TO_VARCHAR(src."BIRTHDATE"), '__NULL__'), COALESCE(TO_VARCHAR(src."MARITALSTATUS"), '__NULL__'), COALESCE(TO_VARCHAR(src."SUFFIX"), '__NULL__'), COALESCE(TO_VARCHAR(src."GENDER"), '__NULL__'), COALESCE(TO_VARCHAR(src."EMAILADDRESS"), '__NULL__'), COALESCE(TO_VARCHAR(src."YEARLYINCOME"), '__NULL__'), COALESCE(TO_VARCHAR(src."TOTALCHILDREN"), '__NULL__'), COALESCE(TO_VARCHAR(src."NUMBERCHILDRENATHOME"), '__NULL__'), COALESCE(TO_VARCHAR(src."ENGLISHEDUCATION"), '__NULL__'), COALESCE(TO_VARCHAR(src."SPANISHEDUCATION"), '__NULL__'), COALESCE(TO_VARCHAR(src."FRENCHEDUCATION"), '__NULL__'), COALESCE(TO_VARCHAR(src."ENGLISHOCCUPATION"), '__NULL__'), COALESCE(TO_VARCHAR(src."SPANISHOCCUPATION"), '__NULL__'), COALESCE(TO_VARCHAR(src."FRENCHOCCUPATION"), '__NULL__'), COALESCE(TO_VARCHAR(src."HOUSEOWNERFLAG"), '__NULL__'), COALESCE(TO_VARCHAR(src."NUMBERCARSOWNED"), '__NULL__'), COALESCE(TO_VARCHAR(src."ADDRESSLINE1"), '__NULL__'), COALESCE(TO_VARCHAR(src."ADDRESSLINE2"), '__NULL__'), COALESCE(TO_VARCHAR(src."PHONE"), '__NULL__'), COALESCE(TO_VARCHAR(src."DATEFIRSTPURCHASE"), '__NULL__'), COALESCE(TO_VARCHAR(src."COMMUTEDISTANCE"), '__NULL__')), 256) AS src_hash
  FROM ADVENTUREWORKS_MIGRATED.STAGING.dim_customer_stg AS src
) AS src
ON tgt."CUSTOMERKEY" = src."CUSTOMERKEY"
  AND tgt."_IS_CURRENT" = TRUE
WHEN MATCHED AND (SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(tgt."GEOGRAPHYKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."CUSTOMERALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."TITLE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."FIRSTNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."MIDDLENAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."LASTNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."NAMESTYLE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."BIRTHDATE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."MARITALSTATUS"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SUFFIX"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."GENDER"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."EMAILADDRESS"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."YEARLYINCOME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."TOTALCHILDREN"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."NUMBERCHILDRENATHOME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ENGLISHEDUCATION"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SPANISHEDUCATION"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."FRENCHEDUCATION"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ENGLISHOCCUPATION"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SPANISHOCCUPATION"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."FRENCHOCCUPATION"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."HOUSEOWNERFLAG"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."NUMBERCARSOWNED"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ADDRESSLINE1"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ADDRESSLINE2"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."PHONE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."DATEFIRSTPURCHASE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."COMMUTEDISTANCE"), '__NULL__')), 256) <> src.src_hash) THEN
  UPDATE SET tgt."_IS_CURRENT" = FALSE, tgt."_VALID_TO" = CURRENT_TIMESTAMP();

MERGE INTO ADVENTUREWORKS_MIGRATED.DW.dim_customer AS tgt
USING (
  SELECT src.*, SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(src."GEOGRAPHYKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."CUSTOMERALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."TITLE"), '__NULL__'), COALESCE(TO_VARCHAR(src."FIRSTNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."MIDDLENAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."LASTNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."NAMESTYLE"), '__NULL__'), COALESCE(TO_VARCHAR(src."BIRTHDATE"), '__NULL__'), COALESCE(TO_VARCHAR(src."MARITALSTATUS"), '__NULL__'), COALESCE(TO_VARCHAR(src."SUFFIX"), '__NULL__'), COALESCE(TO_VARCHAR(src."GENDER"), '__NULL__'), COALESCE(TO_VARCHAR(src."EMAILADDRESS"), '__NULL__'), COALESCE(TO_VARCHAR(src."YEARLYINCOME"), '__NULL__'), COALESCE(TO_VARCHAR(src."TOTALCHILDREN"), '__NULL__'), COALESCE(TO_VARCHAR(src."NUMBERCHILDRENATHOME"), '__NULL__'), COALESCE(TO_VARCHAR(src."ENGLISHEDUCATION"), '__NULL__'), COALESCE(TO_VARCHAR(src."SPANISHEDUCATION"), '__NULL__'), COALESCE(TO_VARCHAR(src."FRENCHEDUCATION"), '__NULL__'), COALESCE(TO_VARCHAR(src."ENGLISHOCCUPATION"), '__NULL__'), COALESCE(TO_VARCHAR(src."SPANISHOCCUPATION"), '__NULL__'), COALESCE(TO_VARCHAR(src."FRENCHOCCUPATION"), '__NULL__'), COALESCE(TO_VARCHAR(src."HOUSEOWNERFLAG"), '__NULL__'), COALESCE(TO_VARCHAR(src."NUMBERCARSOWNED"), '__NULL__'), COALESCE(TO_VARCHAR(src."ADDRESSLINE1"), '__NULL__'), COALESCE(TO_VARCHAR(src."ADDRESSLINE2"), '__NULL__'), COALESCE(TO_VARCHAR(src."PHONE"), '__NULL__'), COALESCE(TO_VARCHAR(src."DATEFIRSTPURCHASE"), '__NULL__'), COALESCE(TO_VARCHAR(src."COMMUTEDISTANCE"), '__NULL__')), 256) AS src_hash
  FROM ADVENTUREWORKS_MIGRATED.STAGING.dim_customer_stg AS src
) AS src
ON tgt."CUSTOMERKEY" = src."CUSTOMERKEY"
  AND tgt."_IS_CURRENT" = TRUE
  AND (SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(tgt."GEOGRAPHYKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."CUSTOMERALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."TITLE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."FIRSTNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."MIDDLENAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."LASTNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."NAMESTYLE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."BIRTHDATE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."MARITALSTATUS"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SUFFIX"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."GENDER"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."EMAILADDRESS"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."YEARLYINCOME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."TOTALCHILDREN"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."NUMBERCHILDRENATHOME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ENGLISHEDUCATION"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SPANISHEDUCATION"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."FRENCHEDUCATION"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ENGLISHOCCUPATION"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SPANISHOCCUPATION"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."FRENCHOCCUPATION"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."HOUSEOWNERFLAG"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."NUMBERCARSOWNED"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ADDRESSLINE1"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ADDRESSLINE2"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."PHONE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."DATEFIRSTPURCHASE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."COMMUTEDISTANCE"), '__NULL__')), 256) = src.src_hash)
WHEN NOT MATCHED THEN
  INSERT ("CUSTOMERKEY", "GEOGRAPHYKEY", "CUSTOMERALTERNATEKEY", "TITLE", "FIRSTNAME", "MIDDLENAME", "LASTNAME", "NAMESTYLE", "BIRTHDATE", "MARITALSTATUS", "SUFFIX", "GENDER", "EMAILADDRESS", "YEARLYINCOME", "TOTALCHILDREN", "NUMBERCHILDRENATHOME", "ENGLISHEDUCATION", "SPANISHEDUCATION", "FRENCHEDUCATION", "ENGLISHOCCUPATION", "SPANISHOCCUPATION", "FRENCHOCCUPATION", "HOUSEOWNERFLAG", "NUMBERCARSOWNED", "ADDRESSLINE1", "ADDRESSLINE2", "PHONE", "DATEFIRSTPURCHASE", "COMMUTEDISTANCE", "_VALID_FROM", "_VALID_TO", "_IS_CURRENT")
  VALUES (src."CUSTOMERKEY", src."GEOGRAPHYKEY", src."CUSTOMERALTERNATEKEY", src."TITLE", src."FIRSTNAME", src."MIDDLENAME", src."LASTNAME", src."NAMESTYLE", src."BIRTHDATE", src."MARITALSTATUS", src."SUFFIX", src."GENDER", src."EMAILADDRESS", src."YEARLYINCOME", src."TOTALCHILDREN", src."NUMBERCHILDRENATHOME", src."ENGLISHEDUCATION", src."SPANISHEDUCATION", src."FRENCHEDUCATION", src."ENGLISHOCCUPATION", src."SPANISHOCCUPATION", src."FRENCHOCCUPATION", src."HOUSEOWNERFLAG", src."NUMBERCARSOWNED", src."ADDRESSLINE1", src."ADDRESSLINE2", src."PHONE", src."DATEFIRSTPURCHASE", src."COMMUTEDISTANCE", CURRENT_TIMESTAMP(), NULL, TRUE);

SELECT 'Applying SCD Type 2 for DW.dim_date from STAGING.dim_date_stg' AS status;
MERGE INTO ADVENTUREWORKS_MIGRATED.DW.dim_date AS tgt
USING (
  SELECT src.*, SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(src."FULLDATEALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."DAYNUMBEROFWEEK"), '__NULL__'), COALESCE(TO_VARCHAR(src."ENGLISHDAYNAMEOFWEEK"), '__NULL__'), COALESCE(TO_VARCHAR(src."SPANISHDAYNAMEOFWEEK"), '__NULL__'), COALESCE(TO_VARCHAR(src."FRENCHDAYNAMEOFWEEK"), '__NULL__'), COALESCE(TO_VARCHAR(src."DAYNUMBEROFMONTH"), '__NULL__'), COALESCE(TO_VARCHAR(src."DAYNUMBEROFYEAR"), '__NULL__'), COALESCE(TO_VARCHAR(src."WEEKNUMBEROFYEAR"), '__NULL__'), COALESCE(TO_VARCHAR(src."ENGLISHMONTHNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."SPANISHMONTHNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."FRENCHMONTHNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."MONTHNUMBEROFYEAR"), '__NULL__'), COALESCE(TO_VARCHAR(src."CALENDARQUARTER"), '__NULL__'), COALESCE(TO_VARCHAR(src."CALENDARYEAR"), '__NULL__'), COALESCE(TO_VARCHAR(src."CALENDARSEMESTER"), '__NULL__'), COALESCE(TO_VARCHAR(src."FISCALQUARTER"), '__NULL__'), COALESCE(TO_VARCHAR(src."FISCALYEAR"), '__NULL__'), COALESCE(TO_VARCHAR(src."FISCALSEMESTER"), '__NULL__')), 256) AS src_hash
  FROM ADVENTUREWORKS_MIGRATED.STAGING.dim_date_stg AS src
) AS src
ON tgt."DATEKEY" = src."DATEKEY"
  AND tgt."_IS_CURRENT" = TRUE
WHEN MATCHED AND (SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(tgt."FULLDATEALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."DAYNUMBEROFWEEK"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ENGLISHDAYNAMEOFWEEK"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SPANISHDAYNAMEOFWEEK"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."FRENCHDAYNAMEOFWEEK"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."DAYNUMBEROFMONTH"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."DAYNUMBEROFYEAR"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."WEEKNUMBEROFYEAR"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ENGLISHMONTHNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SPANISHMONTHNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."FRENCHMONTHNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."MONTHNUMBEROFYEAR"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."CALENDARQUARTER"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."CALENDARYEAR"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."CALENDARSEMESTER"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."FISCALQUARTER"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."FISCALYEAR"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."FISCALSEMESTER"), '__NULL__')), 256) <> src.src_hash) THEN
  UPDATE SET tgt."_IS_CURRENT" = FALSE, tgt."_VALID_TO" = CURRENT_TIMESTAMP();

MERGE INTO ADVENTUREWORKS_MIGRATED.DW.dim_date AS tgt
USING (
  SELECT src.*, SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(src."FULLDATEALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."DAYNUMBEROFWEEK"), '__NULL__'), COALESCE(TO_VARCHAR(src."ENGLISHDAYNAMEOFWEEK"), '__NULL__'), COALESCE(TO_VARCHAR(src."SPANISHDAYNAMEOFWEEK"), '__NULL__'), COALESCE(TO_VARCHAR(src."FRENCHDAYNAMEOFWEEK"), '__NULL__'), COALESCE(TO_VARCHAR(src."DAYNUMBEROFMONTH"), '__NULL__'), COALESCE(TO_VARCHAR(src."DAYNUMBEROFYEAR"), '__NULL__'), COALESCE(TO_VARCHAR(src."WEEKNUMBEROFYEAR"), '__NULL__'), COALESCE(TO_VARCHAR(src."ENGLISHMONTHNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."SPANISHMONTHNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."FRENCHMONTHNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."MONTHNUMBEROFYEAR"), '__NULL__'), COALESCE(TO_VARCHAR(src."CALENDARQUARTER"), '__NULL__'), COALESCE(TO_VARCHAR(src."CALENDARYEAR"), '__NULL__'), COALESCE(TO_VARCHAR(src."CALENDARSEMESTER"), '__NULL__'), COALESCE(TO_VARCHAR(src."FISCALQUARTER"), '__NULL__'), COALESCE(TO_VARCHAR(src."FISCALYEAR"), '__NULL__'), COALESCE(TO_VARCHAR(src."FISCALSEMESTER"), '__NULL__')), 256) AS src_hash
  FROM ADVENTUREWORKS_MIGRATED.STAGING.dim_date_stg AS src
) AS src
ON tgt."DATEKEY" = src."DATEKEY"
  AND tgt."_IS_CURRENT" = TRUE
  AND (SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(tgt."FULLDATEALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."DAYNUMBEROFWEEK"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ENGLISHDAYNAMEOFWEEK"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SPANISHDAYNAMEOFWEEK"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."FRENCHDAYNAMEOFWEEK"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."DAYNUMBEROFMONTH"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."DAYNUMBEROFYEAR"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."WEEKNUMBEROFYEAR"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ENGLISHMONTHNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SPANISHMONTHNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."FRENCHMONTHNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."MONTHNUMBEROFYEAR"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."CALENDARQUARTER"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."CALENDARYEAR"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."CALENDARSEMESTER"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."FISCALQUARTER"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."FISCALYEAR"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."FISCALSEMESTER"), '__NULL__')), 256) = src.src_hash)
WHEN NOT MATCHED THEN
  INSERT ("DATEKEY", "FULLDATEALTERNATEKEY", "DAYNUMBEROFWEEK", "ENGLISHDAYNAMEOFWEEK", "SPANISHDAYNAMEOFWEEK", "FRENCHDAYNAMEOFWEEK", "DAYNUMBEROFMONTH", "DAYNUMBEROFYEAR", "WEEKNUMBEROFYEAR", "ENGLISHMONTHNAME", "SPANISHMONTHNAME", "FRENCHMONTHNAME", "MONTHNUMBEROFYEAR", "CALENDARQUARTER", "CALENDARYEAR", "CALENDARSEMESTER", "FISCALQUARTER", "FISCALYEAR", "FISCALSEMESTER", "_VALID_FROM", "_VALID_TO", "_IS_CURRENT")
  VALUES (src."DATEKEY", src."FULLDATEALTERNATEKEY", src."DAYNUMBEROFWEEK", src."ENGLISHDAYNAMEOFWEEK", src."SPANISHDAYNAMEOFWEEK", src."FRENCHDAYNAMEOFWEEK", src."DAYNUMBEROFMONTH", src."DAYNUMBEROFYEAR", src."WEEKNUMBEROFYEAR", src."ENGLISHMONTHNAME", src."SPANISHMONTHNAME", src."FRENCHMONTHNAME", src."MONTHNUMBEROFYEAR", src."CALENDARQUARTER", src."CALENDARYEAR", src."CALENDARSEMESTER", src."FISCALQUARTER", src."FISCALYEAR", src."FISCALSEMESTER", CURRENT_TIMESTAMP(), NULL, TRUE);

SELECT 'Applying SCD Type 2 for DW.dim_department_group from STAGING.dim_department_group_stg' AS status;
MERGE INTO ADVENTUREWORKS_MIGRATED.DW.dim_department_group AS tgt
USING (
  SELECT src.*, SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(src."PARENTDEPARTMENTGROUPKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."DEPARTMENTGROUPNAME"), '__NULL__')), 256) AS src_hash
  FROM ADVENTUREWORKS_MIGRATED.STAGING.dim_department_group_stg AS src
) AS src
ON tgt."DEPARTMENTGROUPKEY" = src."DEPARTMENTGROUPKEY"
  AND tgt."_IS_CURRENT" = TRUE
WHEN MATCHED AND (SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(tgt."PARENTDEPARTMENTGROUPKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."DEPARTMENTGROUPNAME"), '__NULL__')), 256) <> src.src_hash) THEN
  UPDATE SET tgt."_IS_CURRENT" = FALSE, tgt."_VALID_TO" = CURRENT_TIMESTAMP();

MERGE INTO ADVENTUREWORKS_MIGRATED.DW.dim_department_group AS tgt
USING (
  SELECT src.*, SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(src."PARENTDEPARTMENTGROUPKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."DEPARTMENTGROUPNAME"), '__NULL__')), 256) AS src_hash
  FROM ADVENTUREWORKS_MIGRATED.STAGING.dim_department_group_stg AS src
) AS src
ON tgt."DEPARTMENTGROUPKEY" = src."DEPARTMENTGROUPKEY"
  AND tgt."_IS_CURRENT" = TRUE
  AND (SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(tgt."PARENTDEPARTMENTGROUPKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."DEPARTMENTGROUPNAME"), '__NULL__')), 256) = src.src_hash)
WHEN NOT MATCHED THEN
  INSERT ("DEPARTMENTGROUPKEY", "PARENTDEPARTMENTGROUPKEY", "DEPARTMENTGROUPNAME", "_VALID_FROM", "_VALID_TO", "_IS_CURRENT")
  VALUES (src."DEPARTMENTGROUPKEY", src."PARENTDEPARTMENTGROUPKEY", src."DEPARTMENTGROUPNAME", CURRENT_TIMESTAMP(), NULL, TRUE);

SELECT 'Applying SCD Type 2 for DW.dim_employee from STAGING.dim_employee_stg' AS status;
MERGE INTO ADVENTUREWORKS_MIGRATED.DW.dim_employee AS tgt
USING (
  SELECT src.*, SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(src."PARENTEMPLOYEEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."EMPLOYEENATIONALIDALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."PARENTEMPLOYEENATIONALIDALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."SALESTERRITORYKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."FIRSTNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."LASTNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."MIDDLENAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."NAMESTYLE"), '__NULL__'), COALESCE(TO_VARCHAR(src."TITLE"), '__NULL__'), COALESCE(TO_VARCHAR(src."HIREDATE"), '__NULL__'), COALESCE(TO_VARCHAR(src."BIRTHDATE"), '__NULL__'), COALESCE(TO_VARCHAR(src."LOGINID"), '__NULL__'), COALESCE(TO_VARCHAR(src."EMAILADDRESS"), '__NULL__'), COALESCE(TO_VARCHAR(src."PHONE"), '__NULL__'), COALESCE(TO_VARCHAR(src."MARITALSTATUS"), '__NULL__'), COALESCE(TO_VARCHAR(src."EMERGENCYCONTACTNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."EMERGENCYCONTACTPHONE"), '__NULL__'), COALESCE(TO_VARCHAR(src."SALARIEDFLAG"), '__NULL__'), COALESCE(TO_VARCHAR(src."GENDER"), '__NULL__'), COALESCE(TO_VARCHAR(src."PAYFREQUENCY"), '__NULL__'), COALESCE(TO_VARCHAR(src."BASERATE"), '__NULL__'), COALESCE(TO_VARCHAR(src."VACATIONHOURS"), '__NULL__'), COALESCE(TO_VARCHAR(src."SICKLEAVEHOURS"), '__NULL__'), COALESCE(TO_VARCHAR(src."CURRENTFLAG"), '__NULL__'), COALESCE(TO_VARCHAR(src."SALESPERSONFLAG"), '__NULL__'), COALESCE(TO_VARCHAR(src."DEPARTMENTNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."STARTDATE"), '__NULL__'), COALESCE(TO_VARCHAR(src."ENDDATE"), '__NULL__'), COALESCE(TO_VARCHAR(src."STATUS"), '__NULL__'), COALESCE(TO_VARCHAR(src."EMPLOYEEPHOTO"), '__NULL__')), 256) AS src_hash
  FROM ADVENTUREWORKS_MIGRATED.STAGING.dim_employee_stg AS src
) AS src
ON tgt."EMPLOYEEKEY" = src."EMPLOYEEKEY"
  AND tgt."_IS_CURRENT" = TRUE
WHEN MATCHED AND (SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(tgt."PARENTEMPLOYEEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."EMPLOYEENATIONALIDALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."PARENTEMPLOYEENATIONALIDALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SALESTERRITORYKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."FIRSTNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."LASTNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."MIDDLENAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."NAMESTYLE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."TITLE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."HIREDATE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."BIRTHDATE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."LOGINID"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."EMAILADDRESS"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."PHONE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."MARITALSTATUS"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."EMERGENCYCONTACTNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."EMERGENCYCONTACTPHONE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SALARIEDFLAG"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."GENDER"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."PAYFREQUENCY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."BASERATE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."VACATIONHOURS"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SICKLEAVEHOURS"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."CURRENTFLAG"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SALESPERSONFLAG"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."DEPARTMENTNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."STARTDATE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ENDDATE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."STATUS"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."EMPLOYEEPHOTO"), '__NULL__')), 256) <> src.src_hash) THEN
  UPDATE SET tgt."_IS_CURRENT" = FALSE, tgt."_VALID_TO" = CURRENT_TIMESTAMP();

MERGE INTO ADVENTUREWORKS_MIGRATED.DW.dim_employee AS tgt
USING (
  SELECT src.*, SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(src."PARENTEMPLOYEEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."EMPLOYEENATIONALIDALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."PARENTEMPLOYEENATIONALIDALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."SALESTERRITORYKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."FIRSTNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."LASTNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."MIDDLENAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."NAMESTYLE"), '__NULL__'), COALESCE(TO_VARCHAR(src."TITLE"), '__NULL__'), COALESCE(TO_VARCHAR(src."HIREDATE"), '__NULL__'), COALESCE(TO_VARCHAR(src."BIRTHDATE"), '__NULL__'), COALESCE(TO_VARCHAR(src."LOGINID"), '__NULL__'), COALESCE(TO_VARCHAR(src."EMAILADDRESS"), '__NULL__'), COALESCE(TO_VARCHAR(src."PHONE"), '__NULL__'), COALESCE(TO_VARCHAR(src."MARITALSTATUS"), '__NULL__'), COALESCE(TO_VARCHAR(src."EMERGENCYCONTACTNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."EMERGENCYCONTACTPHONE"), '__NULL__'), COALESCE(TO_VARCHAR(src."SALARIEDFLAG"), '__NULL__'), COALESCE(TO_VARCHAR(src."GENDER"), '__NULL__'), COALESCE(TO_VARCHAR(src."PAYFREQUENCY"), '__NULL__'), COALESCE(TO_VARCHAR(src."BASERATE"), '__NULL__'), COALESCE(TO_VARCHAR(src."VACATIONHOURS"), '__NULL__'), COALESCE(TO_VARCHAR(src."SICKLEAVEHOURS"), '__NULL__'), COALESCE(TO_VARCHAR(src."CURRENTFLAG"), '__NULL__'), COALESCE(TO_VARCHAR(src."SALESPERSONFLAG"), '__NULL__'), COALESCE(TO_VARCHAR(src."DEPARTMENTNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."STARTDATE"), '__NULL__'), COALESCE(TO_VARCHAR(src."ENDDATE"), '__NULL__'), COALESCE(TO_VARCHAR(src."STATUS"), '__NULL__'), COALESCE(TO_VARCHAR(src."EMPLOYEEPHOTO"), '__NULL__')), 256) AS src_hash
  FROM ADVENTUREWORKS_MIGRATED.STAGING.dim_employee_stg AS src
) AS src
ON tgt."EMPLOYEEKEY" = src."EMPLOYEEKEY"
  AND tgt."_IS_CURRENT" = TRUE
  AND (SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(tgt."PARENTEMPLOYEEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."EMPLOYEENATIONALIDALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."PARENTEMPLOYEENATIONALIDALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SALESTERRITORYKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."FIRSTNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."LASTNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."MIDDLENAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."NAMESTYLE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."TITLE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."HIREDATE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."BIRTHDATE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."LOGINID"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."EMAILADDRESS"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."PHONE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."MARITALSTATUS"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."EMERGENCYCONTACTNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."EMERGENCYCONTACTPHONE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SALARIEDFLAG"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."GENDER"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."PAYFREQUENCY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."BASERATE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."VACATIONHOURS"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SICKLEAVEHOURS"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."CURRENTFLAG"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SALESPERSONFLAG"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."DEPARTMENTNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."STARTDATE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ENDDATE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."STATUS"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."EMPLOYEEPHOTO"), '__NULL__')), 256) = src.src_hash)
WHEN NOT MATCHED THEN
  INSERT ("EMPLOYEEKEY", "PARENTEMPLOYEEKEY", "EMPLOYEENATIONALIDALTERNATEKEY", "PARENTEMPLOYEENATIONALIDALTERNATEKEY", "SALESTERRITORYKEY", "FIRSTNAME", "LASTNAME", "MIDDLENAME", "NAMESTYLE", "TITLE", "HIREDATE", "BIRTHDATE", "LOGINID", "EMAILADDRESS", "PHONE", "MARITALSTATUS", "EMERGENCYCONTACTNAME", "EMERGENCYCONTACTPHONE", "SALARIEDFLAG", "GENDER", "PAYFREQUENCY", "BASERATE", "VACATIONHOURS", "SICKLEAVEHOURS", "CURRENTFLAG", "SALESPERSONFLAG", "DEPARTMENTNAME", "STARTDATE", "ENDDATE", "STATUS", "EMPLOYEEPHOTO", "_VALID_FROM", "_VALID_TO", "_IS_CURRENT")
  VALUES (src."EMPLOYEEKEY", src."PARENTEMPLOYEEKEY", src."EMPLOYEENATIONALIDALTERNATEKEY", src."PARENTEMPLOYEENATIONALIDALTERNATEKEY", src."SALESTERRITORYKEY", src."FIRSTNAME", src."LASTNAME", src."MIDDLENAME", src."NAMESTYLE", src."TITLE", src."HIREDATE", src."BIRTHDATE", src."LOGINID", src."EMAILADDRESS", src."PHONE", src."MARITALSTATUS", src."EMERGENCYCONTACTNAME", src."EMERGENCYCONTACTPHONE", src."SALARIEDFLAG", src."GENDER", src."PAYFREQUENCY", src."BASERATE", src."VACATIONHOURS", src."SICKLEAVEHOURS", src."CURRENTFLAG", src."SALESPERSONFLAG", src."DEPARTMENTNAME", src."STARTDATE", src."ENDDATE", src."STATUS", src."EMPLOYEEPHOTO", CURRENT_TIMESTAMP(), NULL, TRUE);

SELECT 'Applying SCD Type 2 for DW.dim_geography from STAGING.dim_geography_stg' AS status;
MERGE INTO ADVENTUREWORKS_MIGRATED.DW.dim_geography AS tgt
USING (
  SELECT src.*, SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(src."CITY"), '__NULL__'), COALESCE(TO_VARCHAR(src."STATEPROVINCECODE"), '__NULL__'), COALESCE(TO_VARCHAR(src."STATEPROVINCENAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."COUNTRYREGIONCODE"), '__NULL__'), COALESCE(TO_VARCHAR(src."ENGLISHCOUNTRYREGIONNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."SPANISHCOUNTRYREGIONNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."FRENCHCOUNTRYREGIONNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."POSTALCODE"), '__NULL__'), COALESCE(TO_VARCHAR(src."SALESTERRITORYKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."IPADDRESSLOCATOR"), '__NULL__')), 256) AS src_hash
  FROM ADVENTUREWORKS_MIGRATED.STAGING.dim_geography_stg AS src
) AS src
ON tgt."GEOGRAPHYKEY" = src."GEOGRAPHYKEY"
  AND tgt."_IS_CURRENT" = TRUE
WHEN MATCHED AND (SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(tgt."CITY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."STATEPROVINCECODE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."STATEPROVINCENAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."COUNTRYREGIONCODE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ENGLISHCOUNTRYREGIONNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SPANISHCOUNTRYREGIONNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."FRENCHCOUNTRYREGIONNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."POSTALCODE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SALESTERRITORYKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."IPADDRESSLOCATOR"), '__NULL__')), 256) <> src.src_hash) THEN
  UPDATE SET tgt."_IS_CURRENT" = FALSE, tgt."_VALID_TO" = CURRENT_TIMESTAMP();

MERGE INTO ADVENTUREWORKS_MIGRATED.DW.dim_geography AS tgt
USING (
  SELECT src.*, SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(src."CITY"), '__NULL__'), COALESCE(TO_VARCHAR(src."STATEPROVINCECODE"), '__NULL__'), COALESCE(TO_VARCHAR(src."STATEPROVINCENAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."COUNTRYREGIONCODE"), '__NULL__'), COALESCE(TO_VARCHAR(src."ENGLISHCOUNTRYREGIONNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."SPANISHCOUNTRYREGIONNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."FRENCHCOUNTRYREGIONNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."POSTALCODE"), '__NULL__'), COALESCE(TO_VARCHAR(src."SALESTERRITORYKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."IPADDRESSLOCATOR"), '__NULL__')), 256) AS src_hash
  FROM ADVENTUREWORKS_MIGRATED.STAGING.dim_geography_stg AS src
) AS src
ON tgt."GEOGRAPHYKEY" = src."GEOGRAPHYKEY"
  AND tgt."_IS_CURRENT" = TRUE
  AND (SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(tgt."CITY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."STATEPROVINCECODE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."STATEPROVINCENAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."COUNTRYREGIONCODE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ENGLISHCOUNTRYREGIONNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SPANISHCOUNTRYREGIONNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."FRENCHCOUNTRYREGIONNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."POSTALCODE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SALESTERRITORYKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."IPADDRESSLOCATOR"), '__NULL__')), 256) = src.src_hash)
WHEN NOT MATCHED THEN
  INSERT ("GEOGRAPHYKEY", "CITY", "STATEPROVINCECODE", "STATEPROVINCENAME", "COUNTRYREGIONCODE", "ENGLISHCOUNTRYREGIONNAME", "SPANISHCOUNTRYREGIONNAME", "FRENCHCOUNTRYREGIONNAME", "POSTALCODE", "SALESTERRITORYKEY", "IPADDRESSLOCATOR", "_VALID_FROM", "_VALID_TO", "_IS_CURRENT")
  VALUES (src."GEOGRAPHYKEY", src."CITY", src."STATEPROVINCECODE", src."STATEPROVINCENAME", src."COUNTRYREGIONCODE", src."ENGLISHCOUNTRYREGIONNAME", src."SPANISHCOUNTRYREGIONNAME", src."FRENCHCOUNTRYREGIONNAME", src."POSTALCODE", src."SALESTERRITORYKEY", src."IPADDRESSLOCATOR", CURRENT_TIMESTAMP(), NULL, TRUE);

SELECT 'Applying SCD Type 2 for DW.dim_organization from STAGING.dim_organization_stg' AS status;
MERGE INTO ADVENTUREWORKS_MIGRATED.DW.dim_organization AS tgt
USING (
  SELECT src.*, SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(src."PARENTORGANIZATIONKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."PERCENTAGEOFOWNERSHIP"), '__NULL__'), COALESCE(TO_VARCHAR(src."ORGANIZATIONNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."CURRENCYKEY"), '__NULL__')), 256) AS src_hash
  FROM ADVENTUREWORKS_MIGRATED.STAGING.dim_organization_stg AS src
) AS src
ON tgt."ORGANIZATIONKEY" = src."ORGANIZATIONKEY"
  AND tgt."_IS_CURRENT" = TRUE
WHEN MATCHED AND (SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(tgt."PARENTORGANIZATIONKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."PERCENTAGEOFOWNERSHIP"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ORGANIZATIONNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."CURRENCYKEY"), '__NULL__')), 256) <> src.src_hash) THEN
  UPDATE SET tgt."_IS_CURRENT" = FALSE, tgt."_VALID_TO" = CURRENT_TIMESTAMP();

MERGE INTO ADVENTUREWORKS_MIGRATED.DW.dim_organization AS tgt
USING (
  SELECT src.*, SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(src."PARENTORGANIZATIONKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."PERCENTAGEOFOWNERSHIP"), '__NULL__'), COALESCE(TO_VARCHAR(src."ORGANIZATIONNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."CURRENCYKEY"), '__NULL__')), 256) AS src_hash
  FROM ADVENTUREWORKS_MIGRATED.STAGING.dim_organization_stg AS src
) AS src
ON tgt."ORGANIZATIONKEY" = src."ORGANIZATIONKEY"
  AND tgt."_IS_CURRENT" = TRUE
  AND (SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(tgt."PARENTORGANIZATIONKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."PERCENTAGEOFOWNERSHIP"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ORGANIZATIONNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."CURRENCYKEY"), '__NULL__')), 256) = src.src_hash)
WHEN NOT MATCHED THEN
  INSERT ("ORGANIZATIONKEY", "PARENTORGANIZATIONKEY", "PERCENTAGEOFOWNERSHIP", "ORGANIZATIONNAME", "CURRENCYKEY", "_VALID_FROM", "_VALID_TO", "_IS_CURRENT")
  VALUES (src."ORGANIZATIONKEY", src."PARENTORGANIZATIONKEY", src."PERCENTAGEOFOWNERSHIP", src."ORGANIZATIONNAME", src."CURRENCYKEY", CURRENT_TIMESTAMP(), NULL, TRUE);

SELECT 'Applying SCD Type 2 for DW.dim_product from STAGING.dim_product_stg' AS status;
MERGE INTO ADVENTUREWORKS_MIGRATED.DW.dim_product AS tgt
USING (
  SELECT src.*, SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(src."PRODUCTALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."PRODUCTSUBCATEGORYKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."WEIGHTUNITMEASURECODE"), '__NULL__'), COALESCE(TO_VARCHAR(src."SIZEUNITMEASURECODE"), '__NULL__'), COALESCE(TO_VARCHAR(src."ENGLISHPRODUCTNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."SPANISHPRODUCTNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."FRENCHPRODUCTNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."STANDARDCOST"), '__NULL__'), COALESCE(TO_VARCHAR(src."FINISHEDGOODSFLAG"), '__NULL__'), COALESCE(TO_VARCHAR(src."COLOR"), '__NULL__'), COALESCE(TO_VARCHAR(src."SAFETYSTOCKLEVEL"), '__NULL__'), COALESCE(TO_VARCHAR(src."REORDERPOINT"), '__NULL__'), COALESCE(TO_VARCHAR(src."LISTPRICE"), '__NULL__'), COALESCE(TO_VARCHAR(src."SIZE"), '__NULL__'), COALESCE(TO_VARCHAR(src."SIZERANGE"), '__NULL__'), COALESCE(TO_VARCHAR(src."WEIGHT"), '__NULL__'), COALESCE(TO_VARCHAR(src."DAYSTOMANUFACTURE"), '__NULL__'), COALESCE(TO_VARCHAR(src."PRODUCTLINE"), '__NULL__'), COALESCE(TO_VARCHAR(src."DEALERPRICE"), '__NULL__'), COALESCE(TO_VARCHAR(src."CLASS"), '__NULL__'), COALESCE(TO_VARCHAR(src."STYLE"), '__NULL__'), COALESCE(TO_VARCHAR(src."MODELNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."LARGEPHOTO"), '__NULL__'), COALESCE(TO_VARCHAR(src."ENGLISHDESCRIPTION"), '__NULL__'), COALESCE(TO_VARCHAR(src."FRENCHDESCRIPTION"), '__NULL__'), COALESCE(TO_VARCHAR(src."CHINESEDESCRIPTION"), '__NULL__'), COALESCE(TO_VARCHAR(src."ARABICDESCRIPTION"), '__NULL__'), COALESCE(TO_VARCHAR(src."HEBREWDESCRIPTION"), '__NULL__'), COALESCE(TO_VARCHAR(src."THAIDESCRIPTION"), '__NULL__'), COALESCE(TO_VARCHAR(src."GERMANDESCRIPTION"), '__NULL__'), COALESCE(TO_VARCHAR(src."JAPANESEDESCRIPTION"), '__NULL__'), COALESCE(TO_VARCHAR(src."TURKISHDESCRIPTION"), '__NULL__'), COALESCE(TO_VARCHAR(src."STARTDATE"), '__NULL__'), COALESCE(TO_VARCHAR(src."ENDDATE"), '__NULL__'), COALESCE(TO_VARCHAR(src."STATUS"), '__NULL__')), 256) AS src_hash
  FROM ADVENTUREWORKS_MIGRATED.STAGING.dim_product_stg AS src
) AS src
ON tgt."PRODUCTKEY" = src."PRODUCTKEY"
  AND tgt."_IS_CURRENT" = TRUE
WHEN MATCHED AND (SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(tgt."PRODUCTALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."PRODUCTSUBCATEGORYKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."WEIGHTUNITMEASURECODE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SIZEUNITMEASURECODE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ENGLISHPRODUCTNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SPANISHPRODUCTNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."FRENCHPRODUCTNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."STANDARDCOST"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."FINISHEDGOODSFLAG"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."COLOR"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SAFETYSTOCKLEVEL"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."REORDERPOINT"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."LISTPRICE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SIZE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SIZERANGE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."WEIGHT"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."DAYSTOMANUFACTURE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."PRODUCTLINE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."DEALERPRICE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."CLASS"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."STYLE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."MODELNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."LARGEPHOTO"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ENGLISHDESCRIPTION"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."FRENCHDESCRIPTION"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."CHINESEDESCRIPTION"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ARABICDESCRIPTION"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."HEBREWDESCRIPTION"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."THAIDESCRIPTION"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."GERMANDESCRIPTION"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."JAPANESEDESCRIPTION"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."TURKISHDESCRIPTION"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."STARTDATE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ENDDATE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."STATUS"), '__NULL__')), 256) <> src.src_hash) THEN
  UPDATE SET tgt."_IS_CURRENT" = FALSE, tgt."_VALID_TO" = CURRENT_TIMESTAMP();

MERGE INTO ADVENTUREWORKS_MIGRATED.DW.dim_product AS tgt
USING (
  SELECT src.*, SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(src."PRODUCTALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."PRODUCTSUBCATEGORYKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."WEIGHTUNITMEASURECODE"), '__NULL__'), COALESCE(TO_VARCHAR(src."SIZEUNITMEASURECODE"), '__NULL__'), COALESCE(TO_VARCHAR(src."ENGLISHPRODUCTNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."SPANISHPRODUCTNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."FRENCHPRODUCTNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."STANDARDCOST"), '__NULL__'), COALESCE(TO_VARCHAR(src."FINISHEDGOODSFLAG"), '__NULL__'), COALESCE(TO_VARCHAR(src."COLOR"), '__NULL__'), COALESCE(TO_VARCHAR(src."SAFETYSTOCKLEVEL"), '__NULL__'), COALESCE(TO_VARCHAR(src."REORDERPOINT"), '__NULL__'), COALESCE(TO_VARCHAR(src."LISTPRICE"), '__NULL__'), COALESCE(TO_VARCHAR(src."SIZE"), '__NULL__'), COALESCE(TO_VARCHAR(src."SIZERANGE"), '__NULL__'), COALESCE(TO_VARCHAR(src."WEIGHT"), '__NULL__'), COALESCE(TO_VARCHAR(src."DAYSTOMANUFACTURE"), '__NULL__'), COALESCE(TO_VARCHAR(src."PRODUCTLINE"), '__NULL__'), COALESCE(TO_VARCHAR(src."DEALERPRICE"), '__NULL__'), COALESCE(TO_VARCHAR(src."CLASS"), '__NULL__'), COALESCE(TO_VARCHAR(src."STYLE"), '__NULL__'), COALESCE(TO_VARCHAR(src."MODELNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."LARGEPHOTO"), '__NULL__'), COALESCE(TO_VARCHAR(src."ENGLISHDESCRIPTION"), '__NULL__'), COALESCE(TO_VARCHAR(src."FRENCHDESCRIPTION"), '__NULL__'), COALESCE(TO_VARCHAR(src."CHINESEDESCRIPTION"), '__NULL__'), COALESCE(TO_VARCHAR(src."ARABICDESCRIPTION"), '__NULL__'), COALESCE(TO_VARCHAR(src."HEBREWDESCRIPTION"), '__NULL__'), COALESCE(TO_VARCHAR(src."THAIDESCRIPTION"), '__NULL__'), COALESCE(TO_VARCHAR(src."GERMANDESCRIPTION"), '__NULL__'), COALESCE(TO_VARCHAR(src."JAPANESEDESCRIPTION"), '__NULL__'), COALESCE(TO_VARCHAR(src."TURKISHDESCRIPTION"), '__NULL__'), COALESCE(TO_VARCHAR(src."STARTDATE"), '__NULL__'), COALESCE(TO_VARCHAR(src."ENDDATE"), '__NULL__'), COALESCE(TO_VARCHAR(src."STATUS"), '__NULL__')), 256) AS src_hash
  FROM ADVENTUREWORKS_MIGRATED.STAGING.dim_product_stg AS src
) AS src
ON tgt."PRODUCTKEY" = src."PRODUCTKEY"
  AND tgt."_IS_CURRENT" = TRUE
  AND (SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(tgt."PRODUCTALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."PRODUCTSUBCATEGORYKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."WEIGHTUNITMEASURECODE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SIZEUNITMEASURECODE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ENGLISHPRODUCTNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SPANISHPRODUCTNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."FRENCHPRODUCTNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."STANDARDCOST"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."FINISHEDGOODSFLAG"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."COLOR"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SAFETYSTOCKLEVEL"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."REORDERPOINT"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."LISTPRICE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SIZE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SIZERANGE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."WEIGHT"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."DAYSTOMANUFACTURE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."PRODUCTLINE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."DEALERPRICE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."CLASS"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."STYLE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."MODELNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."LARGEPHOTO"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ENGLISHDESCRIPTION"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."FRENCHDESCRIPTION"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."CHINESEDESCRIPTION"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ARABICDESCRIPTION"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."HEBREWDESCRIPTION"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."THAIDESCRIPTION"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."GERMANDESCRIPTION"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."JAPANESEDESCRIPTION"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."TURKISHDESCRIPTION"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."STARTDATE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ENDDATE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."STATUS"), '__NULL__')), 256) = src.src_hash)
WHEN NOT MATCHED THEN
  INSERT ("PRODUCTKEY", "PRODUCTALTERNATEKEY", "PRODUCTSUBCATEGORYKEY", "WEIGHTUNITMEASURECODE", "SIZEUNITMEASURECODE", "ENGLISHPRODUCTNAME", "SPANISHPRODUCTNAME", "FRENCHPRODUCTNAME", "STANDARDCOST", "FINISHEDGOODSFLAG", "COLOR", "SAFETYSTOCKLEVEL", "REORDERPOINT", "LISTPRICE", "SIZE", "SIZERANGE", "WEIGHT", "DAYSTOMANUFACTURE", "PRODUCTLINE", "DEALERPRICE", "CLASS", "STYLE", "MODELNAME", "LARGEPHOTO", "ENGLISHDESCRIPTION", "FRENCHDESCRIPTION", "CHINESEDESCRIPTION", "ARABICDESCRIPTION", "HEBREWDESCRIPTION", "THAIDESCRIPTION", "GERMANDESCRIPTION", "JAPANESEDESCRIPTION", "TURKISHDESCRIPTION", "STARTDATE", "ENDDATE", "STATUS", "_VALID_FROM", "_VALID_TO", "_IS_CURRENT")
  VALUES (src."PRODUCTKEY", src."PRODUCTALTERNATEKEY", src."PRODUCTSUBCATEGORYKEY", src."WEIGHTUNITMEASURECODE", src."SIZEUNITMEASURECODE", src."ENGLISHPRODUCTNAME", src."SPANISHPRODUCTNAME", src."FRENCHPRODUCTNAME", src."STANDARDCOST", src."FINISHEDGOODSFLAG", src."COLOR", src."SAFETYSTOCKLEVEL", src."REORDERPOINT", src."LISTPRICE", src."SIZE", src."SIZERANGE", src."WEIGHT", src."DAYSTOMANUFACTURE", src."PRODUCTLINE", src."DEALERPRICE", src."CLASS", src."STYLE", src."MODELNAME", src."LARGEPHOTO", src."ENGLISHDESCRIPTION", src."FRENCHDESCRIPTION", src."CHINESEDESCRIPTION", src."ARABICDESCRIPTION", src."HEBREWDESCRIPTION", src."THAIDESCRIPTION", src."GERMANDESCRIPTION", src."JAPANESEDESCRIPTION", src."TURKISHDESCRIPTION", src."STARTDATE", src."ENDDATE", src."STATUS", CURRENT_TIMESTAMP(), NULL, TRUE);

SELECT 'Applying SCD Type 2 for DW.dim_product_category from STAGING.dim_product_category_stg' AS status;
MERGE INTO ADVENTUREWORKS_MIGRATED.DW.dim_product_category AS tgt
USING (
  SELECT src.*, SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(src."PRODUCTCATEGORYALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."ENGLISHPRODUCTCATEGORYNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."SPANISHPRODUCTCATEGORYNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."FRENCHPRODUCTCATEGORYNAME"), '__NULL__')), 256) AS src_hash
  FROM ADVENTUREWORKS_MIGRATED.STAGING.dim_product_category_stg AS src
) AS src
ON tgt."PRODUCTCATEGORYKEY" = src."PRODUCTCATEGORYKEY"
  AND tgt."_IS_CURRENT" = TRUE
WHEN MATCHED AND (SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(tgt."PRODUCTCATEGORYALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ENGLISHPRODUCTCATEGORYNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SPANISHPRODUCTCATEGORYNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."FRENCHPRODUCTCATEGORYNAME"), '__NULL__')), 256) <> src.src_hash) THEN
  UPDATE SET tgt."_IS_CURRENT" = FALSE, tgt."_VALID_TO" = CURRENT_TIMESTAMP();

MERGE INTO ADVENTUREWORKS_MIGRATED.DW.dim_product_category AS tgt
USING (
  SELECT src.*, SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(src."PRODUCTCATEGORYALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."ENGLISHPRODUCTCATEGORYNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."SPANISHPRODUCTCATEGORYNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."FRENCHPRODUCTCATEGORYNAME"), '__NULL__')), 256) AS src_hash
  FROM ADVENTUREWORKS_MIGRATED.STAGING.dim_product_category_stg AS src
) AS src
ON tgt."PRODUCTCATEGORYKEY" = src."PRODUCTCATEGORYKEY"
  AND tgt."_IS_CURRENT" = TRUE
  AND (SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(tgt."PRODUCTCATEGORYALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ENGLISHPRODUCTCATEGORYNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SPANISHPRODUCTCATEGORYNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."FRENCHPRODUCTCATEGORYNAME"), '__NULL__')), 256) = src.src_hash)
WHEN NOT MATCHED THEN
  INSERT ("PRODUCTCATEGORYKEY", "PRODUCTCATEGORYALTERNATEKEY", "ENGLISHPRODUCTCATEGORYNAME", "SPANISHPRODUCTCATEGORYNAME", "FRENCHPRODUCTCATEGORYNAME", "_VALID_FROM", "_VALID_TO", "_IS_CURRENT")
  VALUES (src."PRODUCTCATEGORYKEY", src."PRODUCTCATEGORYALTERNATEKEY", src."ENGLISHPRODUCTCATEGORYNAME", src."SPANISHPRODUCTCATEGORYNAME", src."FRENCHPRODUCTCATEGORYNAME", CURRENT_TIMESTAMP(), NULL, TRUE);

SELECT 'Applying SCD Type 2 for DW.dim_product_subcategory from STAGING.dim_product_subcategory_stg' AS status;
MERGE INTO ADVENTUREWORKS_MIGRATED.DW.dim_product_subcategory AS tgt
USING (
  SELECT src.*, SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(src."PRODUCTSUBCATEGORYALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."ENGLISHPRODUCTSUBCATEGORYNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."SPANISHPRODUCTSUBCATEGORYNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."FRENCHPRODUCTSUBCATEGORYNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."PRODUCTCATEGORYKEY"), '__NULL__')), 256) AS src_hash
  FROM ADVENTUREWORKS_MIGRATED.STAGING.dim_product_subcategory_stg AS src
) AS src
ON tgt."PRODUCTSUBCATEGORYKEY" = src."PRODUCTSUBCATEGORYKEY"
  AND tgt."_IS_CURRENT" = TRUE
WHEN MATCHED AND (SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(tgt."PRODUCTSUBCATEGORYALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ENGLISHPRODUCTSUBCATEGORYNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SPANISHPRODUCTSUBCATEGORYNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."FRENCHPRODUCTSUBCATEGORYNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."PRODUCTCATEGORYKEY"), '__NULL__')), 256) <> src.src_hash) THEN
  UPDATE SET tgt."_IS_CURRENT" = FALSE, tgt."_VALID_TO" = CURRENT_TIMESTAMP();

MERGE INTO ADVENTUREWORKS_MIGRATED.DW.dim_product_subcategory AS tgt
USING (
  SELECT src.*, SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(src."PRODUCTSUBCATEGORYALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."ENGLISHPRODUCTSUBCATEGORYNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."SPANISHPRODUCTSUBCATEGORYNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."FRENCHPRODUCTSUBCATEGORYNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."PRODUCTCATEGORYKEY"), '__NULL__')), 256) AS src_hash
  FROM ADVENTUREWORKS_MIGRATED.STAGING.dim_product_subcategory_stg AS src
) AS src
ON tgt."PRODUCTSUBCATEGORYKEY" = src."PRODUCTSUBCATEGORYKEY"
  AND tgt."_IS_CURRENT" = TRUE
  AND (SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(tgt."PRODUCTSUBCATEGORYALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ENGLISHPRODUCTSUBCATEGORYNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SPANISHPRODUCTSUBCATEGORYNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."FRENCHPRODUCTSUBCATEGORYNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."PRODUCTCATEGORYKEY"), '__NULL__')), 256) = src.src_hash)
WHEN NOT MATCHED THEN
  INSERT ("PRODUCTSUBCATEGORYKEY", "PRODUCTSUBCATEGORYALTERNATEKEY", "ENGLISHPRODUCTSUBCATEGORYNAME", "SPANISHPRODUCTSUBCATEGORYNAME", "FRENCHPRODUCTSUBCATEGORYNAME", "PRODUCTCATEGORYKEY", "_VALID_FROM", "_VALID_TO", "_IS_CURRENT")
  VALUES (src."PRODUCTSUBCATEGORYKEY", src."PRODUCTSUBCATEGORYALTERNATEKEY", src."ENGLISHPRODUCTSUBCATEGORYNAME", src."SPANISHPRODUCTSUBCATEGORYNAME", src."FRENCHPRODUCTSUBCATEGORYNAME", src."PRODUCTCATEGORYKEY", CURRENT_TIMESTAMP(), NULL, TRUE);

SELECT 'Applying SCD Type 2 for DW.dim_promotion from STAGING.dim_promotion_stg' AS status;
MERGE INTO ADVENTUREWORKS_MIGRATED.DW.dim_promotion AS tgt
USING (
  SELECT src.*, SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(src."PROMOTIONALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."ENGLISHPROMOTIONNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."SPANISHPROMOTIONNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."FRENCHPROMOTIONNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."DISCOUNTPCT"), '__NULL__'), COALESCE(TO_VARCHAR(src."ENGLISHPROMOTIONTYPE"), '__NULL__'), COALESCE(TO_VARCHAR(src."SPANISHPROMOTIONTYPE"), '__NULL__'), COALESCE(TO_VARCHAR(src."FRENCHPROMOTIONTYPE"), '__NULL__'), COALESCE(TO_VARCHAR(src."ENGLISHPROMOTIONCATEGORY"), '__NULL__'), COALESCE(TO_VARCHAR(src."SPANISHPROMOTIONCATEGORY"), '__NULL__'), COALESCE(TO_VARCHAR(src."FRENCHPROMOTIONCATEGORY"), '__NULL__'), COALESCE(TO_VARCHAR(src."STARTDATE"), '__NULL__'), COALESCE(TO_VARCHAR(src."ENDDATE"), '__NULL__'), COALESCE(TO_VARCHAR(src."MINQTY"), '__NULL__'), COALESCE(TO_VARCHAR(src."MAXQTY"), '__NULL__')), 256) AS src_hash
  FROM ADVENTUREWORKS_MIGRATED.STAGING.dim_promotion_stg AS src
) AS src
ON tgt."PROMOTIONKEY" = src."PROMOTIONKEY"
  AND tgt."_IS_CURRENT" = TRUE
WHEN MATCHED AND (SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(tgt."PROMOTIONALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ENGLISHPROMOTIONNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SPANISHPROMOTIONNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."FRENCHPROMOTIONNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."DISCOUNTPCT"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ENGLISHPROMOTIONTYPE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SPANISHPROMOTIONTYPE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."FRENCHPROMOTIONTYPE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ENGLISHPROMOTIONCATEGORY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SPANISHPROMOTIONCATEGORY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."FRENCHPROMOTIONCATEGORY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."STARTDATE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ENDDATE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."MINQTY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."MAXQTY"), '__NULL__')), 256) <> src.src_hash) THEN
  UPDATE SET tgt."_IS_CURRENT" = FALSE, tgt."_VALID_TO" = CURRENT_TIMESTAMP();

MERGE INTO ADVENTUREWORKS_MIGRATED.DW.dim_promotion AS tgt
USING (
  SELECT src.*, SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(src."PROMOTIONALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."ENGLISHPROMOTIONNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."SPANISHPROMOTIONNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."FRENCHPROMOTIONNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."DISCOUNTPCT"), '__NULL__'), COALESCE(TO_VARCHAR(src."ENGLISHPROMOTIONTYPE"), '__NULL__'), COALESCE(TO_VARCHAR(src."SPANISHPROMOTIONTYPE"), '__NULL__'), COALESCE(TO_VARCHAR(src."FRENCHPROMOTIONTYPE"), '__NULL__'), COALESCE(TO_VARCHAR(src."ENGLISHPROMOTIONCATEGORY"), '__NULL__'), COALESCE(TO_VARCHAR(src."SPANISHPROMOTIONCATEGORY"), '__NULL__'), COALESCE(TO_VARCHAR(src."FRENCHPROMOTIONCATEGORY"), '__NULL__'), COALESCE(TO_VARCHAR(src."STARTDATE"), '__NULL__'), COALESCE(TO_VARCHAR(src."ENDDATE"), '__NULL__'), COALESCE(TO_VARCHAR(src."MINQTY"), '__NULL__'), COALESCE(TO_VARCHAR(src."MAXQTY"), '__NULL__')), 256) AS src_hash
  FROM ADVENTUREWORKS_MIGRATED.STAGING.dim_promotion_stg AS src
) AS src
ON tgt."PROMOTIONKEY" = src."PROMOTIONKEY"
  AND tgt."_IS_CURRENT" = TRUE
  AND (SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(tgt."PROMOTIONALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ENGLISHPROMOTIONNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SPANISHPROMOTIONNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."FRENCHPROMOTIONNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."DISCOUNTPCT"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ENGLISHPROMOTIONTYPE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SPANISHPROMOTIONTYPE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."FRENCHPROMOTIONTYPE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ENGLISHPROMOTIONCATEGORY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SPANISHPROMOTIONCATEGORY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."FRENCHPROMOTIONCATEGORY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."STARTDATE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ENDDATE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."MINQTY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."MAXQTY"), '__NULL__')), 256) = src.src_hash)
WHEN NOT MATCHED THEN
  INSERT ("PROMOTIONKEY", "PROMOTIONALTERNATEKEY", "ENGLISHPROMOTIONNAME", "SPANISHPROMOTIONNAME", "FRENCHPROMOTIONNAME", "DISCOUNTPCT", "ENGLISHPROMOTIONTYPE", "SPANISHPROMOTIONTYPE", "FRENCHPROMOTIONTYPE", "ENGLISHPROMOTIONCATEGORY", "SPANISHPROMOTIONCATEGORY", "FRENCHPROMOTIONCATEGORY", "STARTDATE", "ENDDATE", "MINQTY", "MAXQTY", "_VALID_FROM", "_VALID_TO", "_IS_CURRENT")
  VALUES (src."PROMOTIONKEY", src."PROMOTIONALTERNATEKEY", src."ENGLISHPROMOTIONNAME", src."SPANISHPROMOTIONNAME", src."FRENCHPROMOTIONNAME", src."DISCOUNTPCT", src."ENGLISHPROMOTIONTYPE", src."SPANISHPROMOTIONTYPE", src."FRENCHPROMOTIONTYPE", src."ENGLISHPROMOTIONCATEGORY", src."SPANISHPROMOTIONCATEGORY", src."FRENCHPROMOTIONCATEGORY", src."STARTDATE", src."ENDDATE", src."MINQTY", src."MAXQTY", CURRENT_TIMESTAMP(), NULL, TRUE);

SELECT 'Applying SCD Type 2 for DW.dim_prospective_buyer from STAGING.prospective_buyer_stg' AS status;
MERGE INTO ADVENTUREWORKS_MIGRATED.DW.dim_prospective_buyer AS tgt
USING (
  SELECT src.*, SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(src."PROSPECTALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."FIRSTNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."MIDDLENAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."LASTNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."BIRTHDATE"), '__NULL__'), COALESCE(TO_VARCHAR(src."MARITALSTATUS"), '__NULL__'), COALESCE(TO_VARCHAR(src."GENDER"), '__NULL__'), COALESCE(TO_VARCHAR(src."EMAILADDRESS"), '__NULL__'), COALESCE(TO_VARCHAR(src."YEARLYINCOME"), '__NULL__'), COALESCE(TO_VARCHAR(src."TOTALCHILDREN"), '__NULL__'), COALESCE(TO_VARCHAR(src."NUMBERCHILDRENATHOME"), '__NULL__'), COALESCE(TO_VARCHAR(src."EDUCATION"), '__NULL__'), COALESCE(TO_VARCHAR(src."OCCUPATION"), '__NULL__'), COALESCE(TO_VARCHAR(src."HOUSEOWNERFLAG"), '__NULL__'), COALESCE(TO_VARCHAR(src."NUMBERCARSOWNED"), '__NULL__'), COALESCE(TO_VARCHAR(src."ADDRESSLINE1"), '__NULL__'), COALESCE(TO_VARCHAR(src."ADDRESSLINE2"), '__NULL__'), COALESCE(TO_VARCHAR(src."CITY"), '__NULL__'), COALESCE(TO_VARCHAR(src."STATEPROVINCECODE"), '__NULL__'), COALESCE(TO_VARCHAR(src."POSTALCODE"), '__NULL__'), COALESCE(TO_VARCHAR(src."PHONE"), '__NULL__'), COALESCE(TO_VARCHAR(src."SALUTATION"), '__NULL__'), COALESCE(TO_VARCHAR(src."UNKNOWN"), '__NULL__')), 256) AS src_hash
  FROM ADVENTUREWORKS_MIGRATED.STAGING.prospective_buyer_stg AS src
) AS src
ON tgt."PROSPECTIVEBUYERKEY" = src."PROSPECTIVEBUYERKEY"
  AND tgt."_IS_CURRENT" = TRUE
WHEN MATCHED AND (SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(tgt."PROSPECTALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."FIRSTNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."MIDDLENAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."LASTNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."BIRTHDATE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."MARITALSTATUS"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."GENDER"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."EMAILADDRESS"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."YEARLYINCOME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."TOTALCHILDREN"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."NUMBERCHILDRENATHOME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."EDUCATION"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."OCCUPATION"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."HOUSEOWNERFLAG"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."NUMBERCARSOWNED"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ADDRESSLINE1"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ADDRESSLINE2"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."CITY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."STATEPROVINCECODE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."POSTALCODE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."PHONE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SALUTATION"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."UNKNOWN"), '__NULL__')), 256) <> src.src_hash) THEN
  UPDATE SET tgt."_IS_CURRENT" = FALSE, tgt."_VALID_TO" = CURRENT_TIMESTAMP();

MERGE INTO ADVENTUREWORKS_MIGRATED.DW.dim_prospective_buyer AS tgt
USING (
  SELECT src.*, SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(src."PROSPECTALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."FIRSTNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."MIDDLENAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."LASTNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."BIRTHDATE"), '__NULL__'), COALESCE(TO_VARCHAR(src."MARITALSTATUS"), '__NULL__'), COALESCE(TO_VARCHAR(src."GENDER"), '__NULL__'), COALESCE(TO_VARCHAR(src."EMAILADDRESS"), '__NULL__'), COALESCE(TO_VARCHAR(src."YEARLYINCOME"), '__NULL__'), COALESCE(TO_VARCHAR(src."TOTALCHILDREN"), '__NULL__'), COALESCE(TO_VARCHAR(src."NUMBERCHILDRENATHOME"), '__NULL__'), COALESCE(TO_VARCHAR(src."EDUCATION"), '__NULL__'), COALESCE(TO_VARCHAR(src."OCCUPATION"), '__NULL__'), COALESCE(TO_VARCHAR(src."HOUSEOWNERFLAG"), '__NULL__'), COALESCE(TO_VARCHAR(src."NUMBERCARSOWNED"), '__NULL__'), COALESCE(TO_VARCHAR(src."ADDRESSLINE1"), '__NULL__'), COALESCE(TO_VARCHAR(src."ADDRESSLINE2"), '__NULL__'), COALESCE(TO_VARCHAR(src."CITY"), '__NULL__'), COALESCE(TO_VARCHAR(src."STATEPROVINCECODE"), '__NULL__'), COALESCE(TO_VARCHAR(src."POSTALCODE"), '__NULL__'), COALESCE(TO_VARCHAR(src."PHONE"), '__NULL__'), COALESCE(TO_VARCHAR(src."SALUTATION"), '__NULL__'), COALESCE(TO_VARCHAR(src."UNKNOWN"), '__NULL__')), 256) AS src_hash
  FROM ADVENTUREWORKS_MIGRATED.STAGING.prospective_buyer_stg AS src
) AS src
ON tgt."PROSPECTIVEBUYERKEY" = src."PROSPECTIVEBUYERKEY"
  AND tgt."_IS_CURRENT" = TRUE
  AND (SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(tgt."PROSPECTALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."FIRSTNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."MIDDLENAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."LASTNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."BIRTHDATE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."MARITALSTATUS"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."GENDER"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."EMAILADDRESS"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."YEARLYINCOME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."TOTALCHILDREN"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."NUMBERCHILDRENATHOME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."EDUCATION"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."OCCUPATION"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."HOUSEOWNERFLAG"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."NUMBERCARSOWNED"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ADDRESSLINE1"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ADDRESSLINE2"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."CITY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."STATEPROVINCECODE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."POSTALCODE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."PHONE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SALUTATION"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."UNKNOWN"), '__NULL__')), 256) = src.src_hash)
WHEN NOT MATCHED THEN
  INSERT ("PROSPECTIVEBUYERKEY", "PROSPECTALTERNATEKEY", "FIRSTNAME", "MIDDLENAME", "LASTNAME", "BIRTHDATE", "MARITALSTATUS", "GENDER", "EMAILADDRESS", "YEARLYINCOME", "TOTALCHILDREN", "NUMBERCHILDRENATHOME", "EDUCATION", "OCCUPATION", "HOUSEOWNERFLAG", "NUMBERCARSOWNED", "ADDRESSLINE1", "ADDRESSLINE2", "CITY", "STATEPROVINCECODE", "POSTALCODE", "PHONE", "SALUTATION", "UNKNOWN", "_VALID_FROM", "_VALID_TO", "_IS_CURRENT")
  VALUES (src."PROSPECTIVEBUYERKEY", src."PROSPECTALTERNATEKEY", src."FIRSTNAME", src."MIDDLENAME", src."LASTNAME", src."BIRTHDATE", src."MARITALSTATUS", src."GENDER", src."EMAILADDRESS", src."YEARLYINCOME", src."TOTALCHILDREN", src."NUMBERCHILDRENATHOME", src."EDUCATION", src."OCCUPATION", src."HOUSEOWNERFLAG", src."NUMBERCARSOWNED", src."ADDRESSLINE1", src."ADDRESSLINE2", src."CITY", src."STATEPROVINCECODE", src."POSTALCODE", src."PHONE", src."SALUTATION", src."UNKNOWN", CURRENT_TIMESTAMP(), NULL, TRUE);

SELECT 'Applying SCD Type 2 for DW.dim_reseller from STAGING.dim_reseller_stg' AS status;
MERGE INTO ADVENTUREWORKS_MIGRATED.DW.dim_reseller AS tgt
USING (
  SELECT src.*, SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(src."GEOGRAPHYKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."RESELLERALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."PHONE"), '__NULL__'), COALESCE(TO_VARCHAR(src."BUSINESSTYPE"), '__NULL__'), COALESCE(TO_VARCHAR(src."RESELLERNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."NUMBEREMPLOYEES"), '__NULL__'), COALESCE(TO_VARCHAR(src."ORDERFREQUENCY"), '__NULL__'), COALESCE(TO_VARCHAR(src."ORDERMONTH"), '__NULL__'), COALESCE(TO_VARCHAR(src."FIRSTORDERYEAR"), '__NULL__'), COALESCE(TO_VARCHAR(src."LASTORDERYEAR"), '__NULL__'), COALESCE(TO_VARCHAR(src."PRODUCTLINE"), '__NULL__'), COALESCE(TO_VARCHAR(src."ADDRESSLINE1"), '__NULL__'), COALESCE(TO_VARCHAR(src."ADDRESSLINE2"), '__NULL__'), COALESCE(TO_VARCHAR(src."ANNUALSALES"), '__NULL__'), COALESCE(TO_VARCHAR(src."BANKNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."MINPAYMENTTYPE"), '__NULL__'), COALESCE(TO_VARCHAR(src."MINPAYMENTAMOUNT"), '__NULL__'), COALESCE(TO_VARCHAR(src."ANNUALREVENUE"), '__NULL__'), COALESCE(TO_VARCHAR(src."YEAROPENED"), '__NULL__')), 256) AS src_hash
  FROM ADVENTUREWORKS_MIGRATED.STAGING.dim_reseller_stg AS src
) AS src
ON tgt."RESELLERKEY" = src."RESELLERKEY"
  AND tgt."_IS_CURRENT" = TRUE
WHEN MATCHED AND (SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(tgt."GEOGRAPHYKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."RESELLERALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."PHONE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."BUSINESSTYPE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."RESELLERNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."NUMBEREMPLOYEES"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ORDERFREQUENCY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ORDERMONTH"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."FIRSTORDERYEAR"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."LASTORDERYEAR"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."PRODUCTLINE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ADDRESSLINE1"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ADDRESSLINE2"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ANNUALSALES"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."BANKNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."MINPAYMENTTYPE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."MINPAYMENTAMOUNT"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ANNUALREVENUE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."YEAROPENED"), '__NULL__')), 256) <> src.src_hash) THEN
  UPDATE SET tgt."_IS_CURRENT" = FALSE, tgt."_VALID_TO" = CURRENT_TIMESTAMP();

MERGE INTO ADVENTUREWORKS_MIGRATED.DW.dim_reseller AS tgt
USING (
  SELECT src.*, SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(src."GEOGRAPHYKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."RESELLERALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."PHONE"), '__NULL__'), COALESCE(TO_VARCHAR(src."BUSINESSTYPE"), '__NULL__'), COALESCE(TO_VARCHAR(src."RESELLERNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."NUMBEREMPLOYEES"), '__NULL__'), COALESCE(TO_VARCHAR(src."ORDERFREQUENCY"), '__NULL__'), COALESCE(TO_VARCHAR(src."ORDERMONTH"), '__NULL__'), COALESCE(TO_VARCHAR(src."FIRSTORDERYEAR"), '__NULL__'), COALESCE(TO_VARCHAR(src."LASTORDERYEAR"), '__NULL__'), COALESCE(TO_VARCHAR(src."PRODUCTLINE"), '__NULL__'), COALESCE(TO_VARCHAR(src."ADDRESSLINE1"), '__NULL__'), COALESCE(TO_VARCHAR(src."ADDRESSLINE2"), '__NULL__'), COALESCE(TO_VARCHAR(src."ANNUALSALES"), '__NULL__'), COALESCE(TO_VARCHAR(src."BANKNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."MINPAYMENTTYPE"), '__NULL__'), COALESCE(TO_VARCHAR(src."MINPAYMENTAMOUNT"), '__NULL__'), COALESCE(TO_VARCHAR(src."ANNUALREVENUE"), '__NULL__'), COALESCE(TO_VARCHAR(src."YEAROPENED"), '__NULL__')), 256) AS src_hash
  FROM ADVENTUREWORKS_MIGRATED.STAGING.dim_reseller_stg AS src
) AS src
ON tgt."RESELLERKEY" = src."RESELLERKEY"
  AND tgt."_IS_CURRENT" = TRUE
  AND (SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(tgt."GEOGRAPHYKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."RESELLERALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."PHONE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."BUSINESSTYPE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."RESELLERNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."NUMBEREMPLOYEES"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ORDERFREQUENCY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ORDERMONTH"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."FIRSTORDERYEAR"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."LASTORDERYEAR"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."PRODUCTLINE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ADDRESSLINE1"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ADDRESSLINE2"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ANNUALSALES"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."BANKNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."MINPAYMENTTYPE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."MINPAYMENTAMOUNT"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."ANNUALREVENUE"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."YEAROPENED"), '__NULL__')), 256) = src.src_hash)
WHEN NOT MATCHED THEN
  INSERT ("RESELLERKEY", "GEOGRAPHYKEY", "RESELLERALTERNATEKEY", "PHONE", "BUSINESSTYPE", "RESELLERNAME", "NUMBEREMPLOYEES", "ORDERFREQUENCY", "ORDERMONTH", "FIRSTORDERYEAR", "LASTORDERYEAR", "PRODUCTLINE", "ADDRESSLINE1", "ADDRESSLINE2", "ANNUALSALES", "BANKNAME", "MINPAYMENTTYPE", "MINPAYMENTAMOUNT", "ANNUALREVENUE", "YEAROPENED", "_VALID_FROM", "_VALID_TO", "_IS_CURRENT")
  VALUES (src."RESELLERKEY", src."GEOGRAPHYKEY", src."RESELLERALTERNATEKEY", src."PHONE", src."BUSINESSTYPE", src."RESELLERNAME", src."NUMBEREMPLOYEES", src."ORDERFREQUENCY", src."ORDERMONTH", src."FIRSTORDERYEAR", src."LASTORDERYEAR", src."PRODUCTLINE", src."ADDRESSLINE1", src."ADDRESSLINE2", src."ANNUALSALES", src."BANKNAME", src."MINPAYMENTTYPE", src."MINPAYMENTAMOUNT", src."ANNUALREVENUE", src."YEAROPENED", CURRENT_TIMESTAMP(), NULL, TRUE);

SELECT 'Applying SCD Type 2 for DW.dim_sales_reason from STAGING.dim_sales_reason_stg' AS status;
MERGE INTO ADVENTUREWORKS_MIGRATED.DW.dim_sales_reason AS tgt
USING (
  SELECT src.*, SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(src."SALESREASONALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."SALESREASONNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."SALESREASONREASONTYPE"), '__NULL__')), 256) AS src_hash
  FROM ADVENTUREWORKS_MIGRATED.STAGING.dim_sales_reason_stg AS src
) AS src
ON tgt."SALESREASONKEY" = src."SALESREASONKEY"
  AND tgt."_IS_CURRENT" = TRUE
WHEN MATCHED AND (SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(tgt."SALESREASONALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SALESREASONNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SALESREASONREASONTYPE"), '__NULL__')), 256) <> src.src_hash) THEN
  UPDATE SET tgt."_IS_CURRENT" = FALSE, tgt."_VALID_TO" = CURRENT_TIMESTAMP();

MERGE INTO ADVENTUREWORKS_MIGRATED.DW.dim_sales_reason AS tgt
USING (
  SELECT src.*, SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(src."SALESREASONALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."SALESREASONNAME"), '__NULL__'), COALESCE(TO_VARCHAR(src."SALESREASONREASONTYPE"), '__NULL__')), 256) AS src_hash
  FROM ADVENTUREWORKS_MIGRATED.STAGING.dim_sales_reason_stg AS src
) AS src
ON tgt."SALESREASONKEY" = src."SALESREASONKEY"
  AND tgt."_IS_CURRENT" = TRUE
  AND (SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(tgt."SALESREASONALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SALESREASONNAME"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SALESREASONREASONTYPE"), '__NULL__')), 256) = src.src_hash)
WHEN NOT MATCHED THEN
  INSERT ("SALESREASONKEY", "SALESREASONALTERNATEKEY", "SALESREASONNAME", "SALESREASONREASONTYPE", "_VALID_FROM", "_VALID_TO", "_IS_CURRENT")
  VALUES (src."SALESREASONKEY", src."SALESREASONALTERNATEKEY", src."SALESREASONNAME", src."SALESREASONREASONTYPE", CURRENT_TIMESTAMP(), NULL, TRUE);

SELECT 'Applying SCD Type 2 for DW.dim_sales_territory from STAGING.dim_sales_territory_stg' AS status;
MERGE INTO ADVENTUREWORKS_MIGRATED.DW.dim_sales_territory AS tgt
USING (
  SELECT src.*, SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(src."SALESTERRITORYALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."SALESTERRITORYREGION"), '__NULL__'), COALESCE(TO_VARCHAR(src."SALESTERRITORYCOUNTRY"), '__NULL__'), COALESCE(TO_VARCHAR(src."SALESTERRITORYGROUP"), '__NULL__'), COALESCE(TO_VARCHAR(src."SALESTERRITORYIMAGE"), '__NULL__')), 256) AS src_hash
  FROM ADVENTUREWORKS_MIGRATED.STAGING.dim_sales_territory_stg AS src
) AS src
ON tgt."SALESTERRITORYKEY" = src."SALESTERRITORYKEY"
  AND tgt."_IS_CURRENT" = TRUE
WHEN MATCHED AND (SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(tgt."SALESTERRITORYALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SALESTERRITORYREGION"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SALESTERRITORYCOUNTRY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SALESTERRITORYGROUP"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SALESTERRITORYIMAGE"), '__NULL__')), 256) <> src.src_hash) THEN
  UPDATE SET tgt."_IS_CURRENT" = FALSE, tgt."_VALID_TO" = CURRENT_TIMESTAMP();

MERGE INTO ADVENTUREWORKS_MIGRATED.DW.dim_sales_territory AS tgt
USING (
  SELECT src.*, SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(src."SALESTERRITORYALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(src."SALESTERRITORYREGION"), '__NULL__'), COALESCE(TO_VARCHAR(src."SALESTERRITORYCOUNTRY"), '__NULL__'), COALESCE(TO_VARCHAR(src."SALESTERRITORYGROUP"), '__NULL__'), COALESCE(TO_VARCHAR(src."SALESTERRITORYIMAGE"), '__NULL__')), 256) AS src_hash
  FROM ADVENTUREWORKS_MIGRATED.STAGING.dim_sales_territory_stg AS src
) AS src
ON tgt."SALESTERRITORYKEY" = src."SALESTERRITORYKEY"
  AND tgt."_IS_CURRENT" = TRUE
  AND (SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(tgt."SALESTERRITORYALTERNATEKEY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SALESTERRITORYREGION"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SALESTERRITORYCOUNTRY"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SALESTERRITORYGROUP"), '__NULL__'), COALESCE(TO_VARCHAR(tgt."SALESTERRITORYIMAGE"), '__NULL__')), 256) = src.src_hash)
WHEN NOT MATCHED THEN
  INSERT ("SALESTERRITORYKEY", "SALESTERRITORYALTERNATEKEY", "SALESTERRITORYREGION", "SALESTERRITORYCOUNTRY", "SALESTERRITORYGROUP", "SALESTERRITORYIMAGE", "_VALID_FROM", "_VALID_TO", "_IS_CURRENT")
  VALUES (src."SALESTERRITORYKEY", src."SALESTERRITORYALTERNATEKEY", src."SALESTERRITORYREGION", src."SALESTERRITORYCOUNTRY", src."SALESTERRITORYGROUP", src."SALESTERRITORYIMAGE", CURRENT_TIMESTAMP(), NULL, TRUE);

SELECT 'Applying SCD Type 2 for DW.dim_scenario from STAGING.dim_scenario_stg' AS status;
MERGE INTO ADVENTUREWORKS_MIGRATED.DW.dim_scenario AS tgt
USING (
  SELECT src.*, SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(src."SCENARIONAME"), '__NULL__')), 256) AS src_hash
  FROM ADVENTUREWORKS_MIGRATED.STAGING.dim_scenario_stg AS src
) AS src
ON tgt."SCENARIOKEY" = src."SCENARIOKEY"
  AND tgt."_IS_CURRENT" = TRUE
WHEN MATCHED AND (SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(tgt."SCENARIONAME"), '__NULL__')), 256) <> src.src_hash) THEN
  UPDATE SET tgt."_IS_CURRENT" = FALSE, tgt."_VALID_TO" = CURRENT_TIMESTAMP();

MERGE INTO ADVENTUREWORKS_MIGRATED.DW.dim_scenario AS tgt
USING (
  SELECT src.*, SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(src."SCENARIONAME"), '__NULL__')), 256) AS src_hash
  FROM ADVENTUREWORKS_MIGRATED.STAGING.dim_scenario_stg AS src
) AS src
ON tgt."SCENARIOKEY" = src."SCENARIOKEY"
  AND tgt."_IS_CURRENT" = TRUE
  AND (SHA2(CONCAT_WS('||', COALESCE(TO_VARCHAR(tgt."SCENARIONAME"), '__NULL__')), 256) = src.src_hash)
WHEN NOT MATCHED THEN
  INSERT ("SCENARIOKEY", "SCENARIONAME", "_VALID_FROM", "_VALID_TO", "_IS_CURRENT")
  VALUES (src."SCENARIOKEY", src."SCENARIONAME", CURRENT_TIMESTAMP(), NULL, TRUE);

SELECT 'Upserting DW.fact_additional_international_product_description from STAGING.fact_additional_international_product_description_stg' AS status;
MERGE INTO ADVENTUREWORKS_MIGRATED.DW.fact_additional_international_product_description AS tgt
USING ADVENTUREWORKS_MIGRATED.STAGING.fact_additional_international_product_description_stg AS src
ON tgt."PRODUCTKEY" = src."PRODUCTKEY" AND tgt."CULTURENAME" = src."CULTURENAME"
WHEN MATCHED THEN UPDATE SET tgt."PRODUCTDESCRIPTION" = src."PRODUCTDESCRIPTION"
WHEN NOT MATCHED THEN
  INSERT ("PRODUCTKEY", "CULTURENAME", "PRODUCTDESCRIPTION")
  VALUES (src."PRODUCTKEY", src."CULTURENAME", src."PRODUCTDESCRIPTION");

SELECT 'Upserting DW.fact_call_center from STAGING.fact_call_center_stg' AS status;
MERGE INTO ADVENTUREWORKS_MIGRATED.DW.fact_call_center AS tgt
USING ADVENTUREWORKS_MIGRATED.STAGING.fact_call_center_stg AS src
ON tgt."FACTCALLCENTERID" = src."FACTCALLCENTERID"
WHEN MATCHED THEN UPDATE SET tgt."DATEKEY" = src."DATEKEY", tgt."WAGETYPE" = src."WAGETYPE", tgt."SHIFT" = src."SHIFT", tgt."LEVELONEOPERATORS" = src."LEVELONEOPERATORS", tgt."LEVELTWOOPERATORS" = src."LEVELTWOOPERATORS", tgt."TOTALOPERATORS" = src."TOTALOPERATORS", tgt."CALLS" = src."CALLS", tgt."AUTOMATICRESPONSES" = src."AUTOMATICRESPONSES", tgt."ORDERS" = src."ORDERS", tgt."ISSUESRAISED" = src."ISSUESRAISED", tgt."AVERAGETIMEPERISSUE" = src."AVERAGETIMEPERISSUE", tgt."SERVICEGRADE" = src."SERVICEGRADE", tgt."DATE" = src."DATE"
WHEN NOT MATCHED THEN
  INSERT ("FACTCALLCENTERID", "DATEKEY", "WAGETYPE", "SHIFT", "LEVELONEOPERATORS", "LEVELTWOOPERATORS", "TOTALOPERATORS", "CALLS", "AUTOMATICRESPONSES", "ORDERS", "ISSUESRAISED", "AVERAGETIMEPERISSUE", "SERVICEGRADE", "DATE")
  VALUES (src."FACTCALLCENTERID", src."DATEKEY", src."WAGETYPE", src."SHIFT", src."LEVELONEOPERATORS", src."LEVELTWOOPERATORS", src."TOTALOPERATORS", src."CALLS", src."AUTOMATICRESPONSES", src."ORDERS", src."ISSUESRAISED", src."AVERAGETIMEPERISSUE", src."SERVICEGRADE", src."DATE");

SELECT 'Upserting DW.fact_currency_rate from STAGING.fact_currency_rate_stg' AS status;
MERGE INTO ADVENTUREWORKS_MIGRATED.DW.fact_currency_rate AS tgt
USING ADVENTUREWORKS_MIGRATED.STAGING.fact_currency_rate_stg AS src
ON tgt."CURRENCYKEY" = src."CURRENCYKEY" AND tgt."DATEKEY" = src."DATEKEY"
WHEN MATCHED THEN UPDATE SET tgt."AVERAGERATE" = src."AVERAGERATE", tgt."ENDOFDAYRATE" = src."ENDOFDAYRATE", tgt."DATE" = src."DATE"
WHEN NOT MATCHED THEN
  INSERT ("CURRENCYKEY", "DATEKEY", "AVERAGERATE", "ENDOFDAYRATE", "DATE")
  VALUES (src."CURRENCYKEY", src."DATEKEY", src."AVERAGERATE", src."ENDOFDAYRATE", src."DATE");

SELECT 'Upserting DW.fact_currency_rate_incremental from STAGING.new_fact_currency_rate_stg' AS status;
MERGE INTO ADVENTUREWORKS_MIGRATED.DW.fact_currency_rate_incremental AS tgt
USING ADVENTUREWORKS_MIGRATED.STAGING.new_fact_currency_rate_stg AS src
ON tgt."CURRENCYID" = src."CURRENCYID" AND tgt."CURRENCYDATE" = src."CURRENCYDATE"
WHEN MATCHED THEN UPDATE SET tgt."AVERAGERATE" = src."AVERAGERATE", tgt."ENDOFDAYRATE" = src."ENDOFDAYRATE", tgt."CURRENCYKEY" = src."CURRENCYKEY", tgt."DATEKEY" = src."DATEKEY"
WHEN NOT MATCHED THEN
  INSERT ("AVERAGERATE", "CURRENCYID", "CURRENCYDATE", "ENDOFDAYRATE", "CURRENCYKEY", "DATEKEY")
  VALUES (src."AVERAGERATE", src."CURRENCYID", src."CURRENCYDATE", src."ENDOFDAYRATE", src."CURRENCYKEY", src."DATEKEY");

SELECT 'Upserting DW.fact_finance from STAGING.fact_finance_stg' AS status;
MERGE INTO ADVENTUREWORKS_MIGRATED.DW.fact_finance AS tgt
USING ADVENTUREWORKS_MIGRATED.STAGING.fact_finance_stg AS src
ON tgt."FINANCEKEY" = src."FINANCEKEY"
WHEN MATCHED THEN UPDATE SET tgt."DATEKEY" = src."DATEKEY", tgt."ORGANIZATIONKEY" = src."ORGANIZATIONKEY", tgt."DEPARTMENTGROUPKEY" = src."DEPARTMENTGROUPKEY", tgt."SCENARIOKEY" = src."SCENARIOKEY", tgt."ACCOUNTKEY" = src."ACCOUNTKEY", tgt."AMOUNT" = src."AMOUNT", tgt."DATE" = src."DATE"
WHEN NOT MATCHED THEN
  INSERT ("FINANCEKEY", "DATEKEY", "ORGANIZATIONKEY", "DEPARTMENTGROUPKEY", "SCENARIOKEY", "ACCOUNTKEY", "AMOUNT", "DATE")
  VALUES (src."FINANCEKEY", src."DATEKEY", src."ORGANIZATIONKEY", src."DEPARTMENTGROUPKEY", src."SCENARIOKEY", src."ACCOUNTKEY", src."AMOUNT", src."DATE");

SELECT 'Upserting DW.fact_internet_sales from STAGING.fact_internet_sales_stg' AS status;
MERGE INTO ADVENTUREWORKS_MIGRATED.DW.fact_internet_sales AS tgt
USING ADVENTUREWORKS_MIGRATED.STAGING.fact_internet_sales_stg AS src
ON tgt."SALESORDERNUMBER" = src."SALESORDERNUMBER" AND tgt."SALESORDERLINENUMBER" = src."SALESORDERLINENUMBER"
WHEN MATCHED THEN UPDATE SET tgt."PRODUCTKEY" = src."PRODUCTKEY", tgt."ORDERDATEKEY" = src."ORDERDATEKEY", tgt."DUEDATEKEY" = src."DUEDATEKEY", tgt."SHIPDATEKEY" = src."SHIPDATEKEY", tgt."CUSTOMERKEY" = src."CUSTOMERKEY", tgt."PROMOTIONKEY" = src."PROMOTIONKEY", tgt."CURRENCYKEY" = src."CURRENCYKEY", tgt."SALESTERRITORYKEY" = src."SALESTERRITORYKEY", tgt."REVISIONNUMBER" = src."REVISIONNUMBER", tgt."ORDERQUANTITY" = src."ORDERQUANTITY", tgt."UNITPRICE" = src."UNITPRICE", tgt."EXTENDEDAMOUNT" = src."EXTENDEDAMOUNT", tgt."UNITPRICEDISCOUNTPCT" = src."UNITPRICEDISCOUNTPCT", tgt."DISCOUNTAMOUNT" = src."DISCOUNTAMOUNT", tgt."PRODUCTSTANDARDCOST" = src."PRODUCTSTANDARDCOST", tgt."TOTALPRODUCTCOST" = src."TOTALPRODUCTCOST", tgt."SALESAMOUNT" = src."SALESAMOUNT", tgt."TAXAMT" = src."TAXAMT", tgt."FREIGHT" = src."FREIGHT", tgt."CARRIERTRACKINGNUMBER" = src."CARRIERTRACKINGNUMBER", tgt."CUSTOMERPONUMBER" = src."CUSTOMERPONUMBER", tgt."ORDERDATE" = src."ORDERDATE", tgt."DUEDATE" = src."DUEDATE", tgt."SHIPDATE" = src."SHIPDATE"
WHEN NOT MATCHED THEN
  INSERT ("PRODUCTKEY", "ORDERDATEKEY", "DUEDATEKEY", "SHIPDATEKEY", "CUSTOMERKEY", "PROMOTIONKEY", "CURRENCYKEY", "SALESTERRITORYKEY", "SALESORDERNUMBER", "SALESORDERLINENUMBER", "REVISIONNUMBER", "ORDERQUANTITY", "UNITPRICE", "EXTENDEDAMOUNT", "UNITPRICEDISCOUNTPCT", "DISCOUNTAMOUNT", "PRODUCTSTANDARDCOST", "TOTALPRODUCTCOST", "SALESAMOUNT", "TAXAMT", "FREIGHT", "CARRIERTRACKINGNUMBER", "CUSTOMERPONUMBER", "ORDERDATE", "DUEDATE", "SHIPDATE")
  VALUES (src."PRODUCTKEY", src."ORDERDATEKEY", src."DUEDATEKEY", src."SHIPDATEKEY", src."CUSTOMERKEY", src."PROMOTIONKEY", src."CURRENCYKEY", src."SALESTERRITORYKEY", src."SALESORDERNUMBER", src."SALESORDERLINENUMBER", src."REVISIONNUMBER", src."ORDERQUANTITY", src."UNITPRICE", src."EXTENDEDAMOUNT", src."UNITPRICEDISCOUNTPCT", src."DISCOUNTAMOUNT", src."PRODUCTSTANDARDCOST", src."TOTALPRODUCTCOST", src."SALESAMOUNT", src."TAXAMT", src."FREIGHT", src."CARRIERTRACKINGNUMBER", src."CUSTOMERPONUMBER", src."ORDERDATE", src."DUEDATE", src."SHIPDATE");

SELECT 'Upserting DW.fact_internet_sales_reason from STAGING.fact_internet_sales_reason_stg' AS status;
MERGE INTO ADVENTUREWORKS_MIGRATED.DW.fact_internet_sales_reason AS tgt
USING ADVENTUREWORKS_MIGRATED.STAGING.fact_internet_sales_reason_stg AS src
ON tgt."SALESORDERNUMBER" = src."SALESORDERNUMBER" AND tgt."SALESORDERLINENUMBER" = src."SALESORDERLINENUMBER" AND tgt."SALESREASONKEY" = src."SALESREASONKEY"
WHEN MATCHED THEN UPDATE SET tgt."SALESORDERNUMBER" = src."SALESORDERNUMBER"
WHEN NOT MATCHED THEN
  INSERT ("SALESORDERNUMBER", "SALESORDERLINENUMBER", "SALESREASONKEY")
  VALUES (src."SALESORDERNUMBER", src."SALESORDERLINENUMBER", src."SALESREASONKEY");

SELECT 'Upserting DW.fact_product_inventory from STAGING.fact_product_inventory_stg' AS status;
MERGE INTO ADVENTUREWORKS_MIGRATED.DW.fact_product_inventory AS tgt
USING ADVENTUREWORKS_MIGRATED.STAGING.fact_product_inventory_stg AS src
ON tgt."PRODUCTKEY" = src."PRODUCTKEY" AND tgt."DATEKEY" = src."DATEKEY" AND tgt."MOVEMENTDATE" = src."MOVEMENTDATE"
WHEN MATCHED THEN UPDATE SET tgt."UNITCOST" = src."UNITCOST", tgt."UNITSIN" = src."UNITSIN", tgt."UNITSOUT" = src."UNITSOUT", tgt."UNITSBALANCE" = src."UNITSBALANCE"
WHEN NOT MATCHED THEN
  INSERT ("PRODUCTKEY", "DATEKEY", "MOVEMENTDATE", "UNITCOST", "UNITSIN", "UNITSOUT", "UNITSBALANCE")
  VALUES (src."PRODUCTKEY", src."DATEKEY", src."MOVEMENTDATE", src."UNITCOST", src."UNITSIN", src."UNITSOUT", src."UNITSBALANCE");

SELECT 'Upserting DW.fact_reseller_sales from STAGING.fact_reseller_sales_stg' AS status;
MERGE INTO ADVENTUREWORKS_MIGRATED.DW.fact_reseller_sales AS tgt
USING ADVENTUREWORKS_MIGRATED.STAGING.fact_reseller_sales_stg AS src
ON tgt."SALESORDERNUMBER" = src."SALESORDERNUMBER" AND tgt."SALESORDERLINENUMBER" = src."SALESORDERLINENUMBER"
WHEN MATCHED THEN UPDATE SET tgt."PRODUCTKEY" = src."PRODUCTKEY", tgt."ORDERDATEKEY" = src."ORDERDATEKEY", tgt."DUEDATEKEY" = src."DUEDATEKEY", tgt."SHIPDATEKEY" = src."SHIPDATEKEY", tgt."RESELLERKEY" = src."RESELLERKEY", tgt."EMPLOYEEKEY" = src."EMPLOYEEKEY", tgt."PROMOTIONKEY" = src."PROMOTIONKEY", tgt."CURRENCYKEY" = src."CURRENCYKEY", tgt."SALESTERRITORYKEY" = src."SALESTERRITORYKEY", tgt."REVISIONNUMBER" = src."REVISIONNUMBER", tgt."ORDERQUANTITY" = src."ORDERQUANTITY", tgt."UNITPRICE" = src."UNITPRICE", tgt."EXTENDEDAMOUNT" = src."EXTENDEDAMOUNT", tgt."UNITPRICEDISCOUNTPCT" = src."UNITPRICEDISCOUNTPCT", tgt."DISCOUNTAMOUNT" = src."DISCOUNTAMOUNT", tgt."PRODUCTSTANDARDCOST" = src."PRODUCTSTANDARDCOST", tgt."TOTALPRODUCTCOST" = src."TOTALPRODUCTCOST", tgt."SALESAMOUNT" = src."SALESAMOUNT", tgt."TAXAMT" = src."TAXAMT", tgt."FREIGHT" = src."FREIGHT", tgt."CARRIERTRACKINGNUMBER" = src."CARRIERTRACKINGNUMBER", tgt."CUSTOMERPONUMBER" = src."CUSTOMERPONUMBER", tgt."ORDERDATE" = src."ORDERDATE", tgt."DUEDATE" = src."DUEDATE", tgt."SHIPDATE" = src."SHIPDATE"
WHEN NOT MATCHED THEN
  INSERT ("PRODUCTKEY", "ORDERDATEKEY", "DUEDATEKEY", "SHIPDATEKEY", "RESELLERKEY", "EMPLOYEEKEY", "PROMOTIONKEY", "CURRENCYKEY", "SALESTERRITORYKEY", "SALESORDERNUMBER", "SALESORDERLINENUMBER", "REVISIONNUMBER", "ORDERQUANTITY", "UNITPRICE", "EXTENDEDAMOUNT", "UNITPRICEDISCOUNTPCT", "DISCOUNTAMOUNT", "PRODUCTSTANDARDCOST", "TOTALPRODUCTCOST", "SALESAMOUNT", "TAXAMT", "FREIGHT", "CARRIERTRACKINGNUMBER", "CUSTOMERPONUMBER", "ORDERDATE", "DUEDATE", "SHIPDATE")
  VALUES (src."PRODUCTKEY", src."ORDERDATEKEY", src."DUEDATEKEY", src."SHIPDATEKEY", src."RESELLERKEY", src."EMPLOYEEKEY", src."PROMOTIONKEY", src."CURRENCYKEY", src."SALESTERRITORYKEY", src."SALESORDERNUMBER", src."SALESORDERLINENUMBER", src."REVISIONNUMBER", src."ORDERQUANTITY", src."UNITPRICE", src."EXTENDEDAMOUNT", src."UNITPRICEDISCOUNTPCT", src."DISCOUNTAMOUNT", src."PRODUCTSTANDARDCOST", src."TOTALPRODUCTCOST", src."SALESAMOUNT", src."TAXAMT", src."FREIGHT", src."CARRIERTRACKINGNUMBER", src."CUSTOMERPONUMBER", src."ORDERDATE", src."DUEDATE", src."SHIPDATE");

SELECT 'Upserting DW.fact_sales_quota from STAGING.fact_sales_quota_stg' AS status;
MERGE INTO ADVENTUREWORKS_MIGRATED.DW.fact_sales_quota AS tgt
USING ADVENTUREWORKS_MIGRATED.STAGING.fact_sales_quota_stg AS src
ON tgt."SALESQUOTAKEY" = src."SALESQUOTAKEY"
WHEN MATCHED THEN UPDATE SET tgt."EMPLOYEEKEY" = src."EMPLOYEEKEY", tgt."DATEKEY" = src."DATEKEY", tgt."CALENDARYEAR" = src."CALENDARYEAR", tgt."CALENDARQUARTER" = src."CALENDARQUARTER", tgt."SALESAMOUNTQUOTA" = src."SALESAMOUNTQUOTA", tgt."DATE" = src."DATE"
WHEN NOT MATCHED THEN
  INSERT ("SALESQUOTAKEY", "EMPLOYEEKEY", "DATEKEY", "CALENDARYEAR", "CALENDARQUARTER", "SALESAMOUNTQUOTA", "DATE")
  VALUES (src."SALESQUOTAKEY", src."EMPLOYEEKEY", src."DATEKEY", src."CALENDARYEAR", src."CALENDARQUARTER", src."SALESAMOUNTQUOTA", src."DATE");

SELECT 'Upserting DW.fact_survey_response from STAGING.fact_survey_response_stg' AS status;
MERGE INTO ADVENTUREWORKS_MIGRATED.DW.fact_survey_response AS tgt
USING ADVENTUREWORKS_MIGRATED.STAGING.fact_survey_response_stg AS src
ON tgt."SURVEYRESPONSEKEY" = src."SURVEYRESPONSEKEY"
WHEN MATCHED THEN UPDATE SET tgt."DATEKEY" = src."DATEKEY", tgt."CUSTOMERKEY" = src."CUSTOMERKEY", tgt."PRODUCTCATEGORYKEY" = src."PRODUCTCATEGORYKEY", tgt."ENGLISHPRODUCTCATEGORYNAME" = src."ENGLISHPRODUCTCATEGORYNAME", tgt."PRODUCTSUBCATEGORYKEY" = src."PRODUCTSUBCATEGORYKEY", tgt."ENGLISHPRODUCTSUBCATEGORYNAME" = src."ENGLISHPRODUCTSUBCATEGORYNAME", tgt."DATE" = src."DATE"
WHEN NOT MATCHED THEN
  INSERT ("SURVEYRESPONSEKEY", "DATEKEY", "CUSTOMERKEY", "PRODUCTCATEGORYKEY", "ENGLISHPRODUCTCATEGORYNAME", "PRODUCTSUBCATEGORYKEY", "ENGLISHPRODUCTSUBCATEGORYNAME", "DATE")
  VALUES (src."SURVEYRESPONSEKEY", src."DATEKEY", src."CUSTOMERKEY", src."PRODUCTCATEGORYKEY", src."ENGLISHPRODUCTCATEGORYNAME", src."PRODUCTSUBCATEGORYKEY", src."ENGLISHPRODUCTSUBCATEGORYNAME", src."DATE");

SELECT 'Completed DW load script' AS status;
